"""Compatibility exports derived from the canonical provider manifest."""

from backend.llm_gateway.provider_manifest import (
    DEFAULT_MODEL_BY_PROVIDER,
    SUPPORTED_PROVIDER_TYPES,
    default_model_for_provider,
)

__all__ = [
    "DEFAULT_MODEL_BY_PROVIDER",
    "SUPPORTED_PROVIDER_TYPES",
    "default_model_for_provider",
    "OPENAI_LATEST_MODEL",
    "GOOGLE_LATEST_MODEL",
    "OPENAI_PRO_MODEL",
    "OPENAI_STANDARD_MODEL",
    "OPENAI_FAST_MODEL",
    "OPENAI_NANO_MODEL",
    "OPENAI_LONG_CONTEXT_MODEL",
    "OPENAI_RESEARCH_MODEL",
    "GOOGLE_PRIMARY_MODEL",
    "GOOGLE_FAST_MODEL",
]


OPENAI_LATEST_MODEL = DEFAULT_MODEL_BY_PROVIDER["openai"]
GOOGLE_LATEST_MODEL = DEFAULT_MODEL_BY_PROVIDER["google"]

# Standardized on a single OpenAI model: the manifest default is the only
# OpenAI model used by every compatibility tier.
OPENAI_PRO_MODEL = OPENAI_LATEST_MODEL
OPENAI_STANDARD_MODEL = OPENAI_LATEST_MODEL
OPENAI_FAST_MODEL = OPENAI_LATEST_MODEL
OPENAI_NANO_MODEL = OPENAI_LATEST_MODEL
OPENAI_LONG_CONTEXT_MODEL = OPENAI_LATEST_MODEL
OPENAI_RESEARCH_MODEL = OPENAI_LATEST_MODEL

GOOGLE_PRIMARY_MODEL = GOOGLE_LATEST_MODEL
GOOGLE_FAST_MODEL = GOOGLE_LATEST_MODEL
