# -*- mode: python ; coding: utf-8 -*-

block_cipher = None

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=[],
    datas=[
        ('backend', 'backend'),
        ('core', 'core'),
        ('routes', 'routes'),
        ('utils', 'utils'),
        ('simulation', 'simulation'),

        ('extensions.py', '.'),
        ('models.py', '.'),
        ('core/data', 'core/data'),
    ],
    hiddenimports=[
        'flask',
        'flask_sqlalchemy',
        'flask_migrate',
        'flask_cors',
        'psycopg2',
        'redis',
        'win32api',
        'win32security',
        'win32crypt',
        'langgraph',
        'langchain_core',
        'langsmith',
        'neo4j',
        'pydantic',
        'pydantic_core',
        'pydantic_settings',
        'sqlalchemy.ext.baked',
        'celery.fixups',
        'celery.fixups.flask',
        'celery.fixups.django',
        'kombu.transport.redis',
        'eventlet',
        'eventlet.hubs.epolls',
        'eventlet.hubs.kqueue',
        'eventlet.hubs.selects',
        'dns',
        'pkg_resources.py2_warn',
        'cv2',
        'web3',
        'eth_account',
        'reportlab',
        'pypdf',
        'docx',
        'openai',
        'tiktoken',
        'langchain_openai',
        'langchain_community',
        'merkletools',
        'dotenv',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    [],
    exclude_binaries=True,
    name='DataLogic_Backend',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    console=True,
    disable_windowed_traceback=False,
    argv_emulation=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='DataLogic_Backend',
)
