apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mcpservers.ukg.datalogic.io
spec:
  group: ukg.datalogic.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                image:
                  type: string
                protocol:
                  type: string
                  enum: ["sse", "websocket"]
                replicas:
                  type: integer
                  minimum: 1
                env:
                  type: array
                  items:
                    type: object
                    properties:
                      name: { type: string }
                      value: { type: string }
  scope: Namespaced
  names:
    plural: mcpservers
    singular: mcpserver
    kind: MCPServer
    shortNames:
      - mcp
