apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: ukgnodes.ukg.datalogic.io
spec:
  group: ukg.datalogic.io
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                role:
                  type: string
                  enum: ["coordinator", "worker"]
                personas:
                  type: array
                  items:
                    type: string
                replicas:
                  type: integer
                  minimum: 1
                image:
                  type: string
                resources:
                  type: object
                  properties:
                    limits:
                      type: object
                      properties:
                        cpu: { type: string }
                        memory: { type: string }
                    requests:
                      type: object
                      properties:
                        cpu: { type: string }
                        memory: { type: string }
  scope: Namespaced
  names:
    plural: ukgnodes
    singular: ukgnode
    kind: UKGNode
    shortNames:
      - un
