
from flask import Blueprint, request, jsonify
from flask_jwt_extended import jwt_required, get_jwt_identity
from .models import db, Chat, Message, User

chat_bp = Blueprint('chat', __name__)

@chat_bp.route('/chats', methods=['GET'])
@jwt_required()
def get_chats():
    user_id = get_jwt_identity()
    
    chats = Chat.query.filter_by(user_id=user_id).order_by(Chat.created_at.desc()).all()
    
    return jsonify([chat.to_dict() for chat in chats]), 200

@chat_bp.route('/chats', methods=['POST'])
@jwt_required()
def create_chat():
    user_id = get_jwt_identity()
    data = request.get_json()
    
    new_chat = Chat(
        title=data.get('title', 'New Chat'),
        user_id=user_id
    )
    
    db.session.add(new_chat)
    db.session.commit()
    
    return jsonify(new_chat.to_dict()), 201

@chat_bp.route('/chats/<int:chat_id>', methods=['GET'])
@jwt_required()
def get_chat(chat_id):
    user_id = get_jwt_identity()
    
    chat = Chat.query.filter_by(id=chat_id, user_id=user_id).first()
    
    if not chat:
        return jsonify({'error': 'Chat not found'}), 404
    
    messages = Message.query.filter_by(chat_id=chat_id).order_by(Message.created_at).all()
    
    return jsonify({
        'chat': chat.to_dict(),
        'messages': [message.to_dict() for message in messages]
    }), 200

@chat_bp.route('/chats/<int:chat_id>/messages', methods=['POST'])
@jwt_required()
def add_message(chat_id):
    user_id = get_jwt_identity()
    data = request.get_json()
    
    # Validate input
    if not data or not data.get('content'):
        return jsonify({'error': 'Message content is required'}), 400
    
    chat = Chat.query.filter_by(id=chat_id, user_id=user_id).first()
    
    if not chat:
        return jsonify({'error': 'Chat not found'}), 404
    
    # Add user message
    user_message = Message(
        chat_id=chat_id,
        role='user',
        content=data['content']
    )
    
    db.session.add(user_message)
    
    # Process with UKG system (simplified for this example)
    # In a real app, you would call your UKG processing logic here
    assistant_response = "This is a placeholder response from the UKG system. In a real implementation, this would be generated by processing your query through the Universal Knowledge Graph."
    
    # Add assistant message
    assistant_message = Message(
        chat_id=chat_id,
        role='assistant',
        content=assistant_response
    )
    
    db.session.add(assistant_message)
    db.session.commit()
    
    return jsonify({
        'user_message': user_message.to_dict(),
        'assistant_message': assistant_message.to_dict()
    }), 201
