"""Subsystem profile registries for persona scaling."""

from core.persona.quad.pod_models import SubsystemProfile


DEFENSE_SUBSYSTEM_PROFILES = {
    "radar": SubsystemProfile(
        subsystem_id="radar_sme",
        name="Radar Systems SME",
        domain="avionics",
        specialization="Active Electronically Scanned Array (AESA) radar systems",
        keywords=["radar", "aesa", "apg", "detection", "tracking", "modes"],
        required_certifications=["Security Clearance", "Radar Systems Certification"],
        related_standards=["MIL-STD-461", "MIL-STD-464"],
        job_role={"title": "Radar Systems Engineer", "level": "Principal"},
        education={"degree": "MS/PhD Electrical Engineering", "focus": "RF Systems"},
        skills={"items": ["Antenna Design", "Signal Processing", "RF Engineering"]},
    ),
    "ew": SubsystemProfile(
        subsystem_id="ew_sme",
        name="Electronic Warfare SME",
        domain="avionics",
        specialization="Electronic attack, protection, and support systems",
        keywords=["electronic warfare", "ew", "jamming", "countermeasures", "rwr", "ecm"],
        required_certifications=["Security Clearance", "EW Systems"],
        related_standards=["MIL-STD-461", "MIL-STD-464"],
        job_role={"title": "EW Systems Engineer", "level": "Senior"},
        education={"degree": "MS Electrical Engineering", "focus": "Electronic Warfare"},
        skills={"items": ["Signal Processing", "Threat Analysis", "Countermeasures Design"]},
    ),
    "avionics": SubsystemProfile(
        subsystem_id="avionics_sme",
        name="Mission Computer / Avionics SME",
        domain="avionics",
        specialization="Integrated avionics and mission computer systems",
        keywords=["avionics", "mission computer", "integrated", "cockpit", "displays"],
        required_certifications=["DO-178C", "Security Clearance"],
        related_standards=["DO-178C", "DO-254", "MIL-STD-1553"],
        job_role={"title": "Avionics Systems Engineer", "level": "Principal"},
        education={"degree": "MS Computer Engineering", "focus": "Embedded Systems"},
        skills={"items": ["Real-time Systems", "Ada/C++", "Avionics Integration"]},
    ),
    "datalink": SubsystemProfile(
        subsystem_id="datalink_sme",
        name="Datalink / Communications SME",
        domain="communications",
        specialization="Tactical datalinks and secure communications",
        keywords=["datalink", "link 16", "communications", "satcom", "secure"],
        required_certifications=["Security Clearance", "COMSEC"],
        related_standards=["MIL-STD-6016", "STANAG 5516"],
        job_role={"title": "Communications Systems Engineer", "level": "Senior"},
        education={"degree": "MS Electrical Engineering", "focus": "Communications"},
        skills={"items": ["Waveform Design", "Network Protocols", "Cryptography"]},
    ),
    "propulsion": SubsystemProfile(
        subsystem_id="propulsion_sme",
        name="Propulsion SME",
        domain="propulsion",
        specialization="Turbofan engines and propulsion systems",
        keywords=["propulsion", "engine", "turbofan", "thrust", "afterburner"],
        required_certifications=["FAA/DoD Propulsion"],
        related_standards=["MIL-E-5007", "MIL-STD-1783"],
        job_role={"title": "Propulsion Engineer", "level": "Senior"},
        education={"degree": "MS Aerospace Engineering", "focus": "Propulsion"},
        skills={"items": ["Thermodynamics", "Turbomachinery", "Performance Analysis"]},
    ),
    "structures": SubsystemProfile(
        subsystem_id="structures_sme",
        name="Airframe Structures SME",
        domain="structures",
        specialization="Aircraft structural design and analysis",
        keywords=["structure", "airframe", "composite", "fatigue", "stress"],
        required_certifications=["Structural Analysis Certification"],
        related_standards=["MIL-STD-1530", "MIL-HDBK-5"],
        job_role={"title": "Structural Engineer", "level": "Senior"},
        education={"degree": "MS Aerospace/Mechanical Engineering"},
        skills={"items": ["FEA", "Composite Materials", "Fatigue Analysis"]},
    ),
    "software": SubsystemProfile(
        subsystem_id="software_sme",
        name="Software / Integration SME",
        domain="software",
        specialization="Mission software and system integration",
        keywords=["software", "integration", "oop", "operational flight program", "ofp"],
        required_certifications=["DO-178C", "CMMI"],
        related_standards=["DO-178C", "MIL-STD-498"],
        job_role={"title": "Software Systems Engineer", "level": "Principal"},
        education={"degree": "MS Computer Science/Software Engineering"},
        skills={"items": ["Ada", "Real-time Systems", "Integration Testing"]},
    ),
    "test": SubsystemProfile(
        subsystem_id="test_sme",
        name="Test & Evaluation SME",
        domain="test",
        specialization="Developmental and operational test and evaluation",
        keywords=["test", "evaluation", "dte", "ote", "flight test", "verification"],
        required_certifications=["Test Pilot School", "DT&E Certification"],
        related_standards=["MIL-STD-810", "MIL-STD-461"],
        job_role={"title": "Test Engineer", "level": "Senior"},
        education={"degree": "MS Engineering", "focus": "Flight Test"},
        skills={"items": ["Test Planning", "Data Analysis", "Requirements Verification"]},
    ),
}

SECTOR_SUBSYSTEM_PROFILES = {
    "program": SubsystemProfile(
        subsystem_id="program_sme",
        name="Program Execution (Cost/Schedule)",
        domain="program_management",
        specialization="Defense acquisition and program management",
        keywords=["program", "cost", "schedule", "milestone", "acquisition", "budget"],
        required_certifications=["PMP", "DAU Level III"],
        related_standards=["FAR", "DFARS", "DoD 5000"],
        job_role={"title": "Program Manager", "level": "Director"},
        education={"degree": "MBA/MS Program Management"},
        skills={"items": ["Earned Value", "Schedule Management", "Risk Management"]},
    ),
    "sustainment": SubsystemProfile(
        subsystem_id="sustainment_sme",
        name="Sustainment / Depot / Readiness",
        domain="sustainment",
        specialization="Weapon system sustainment and readiness",
        keywords=["sustainment", "readiness", "depot", "maintenance", "logistics"],
        required_certifications=["DAWIA Logistics"],
        related_standards=["MIL-STD-1388", "GEIA-STD-0007"],
        job_role={"title": "Sustainment Manager", "level": "Senior"},
        education={"degree": "MS Logistics/Engineering"},
        skills={"items": ["Reliability Engineering", "Supply Chain", "Depot Operations"]},
    ),
    "manufacturing": SubsystemProfile(
        subsystem_id="manufacturing_sme",
        name="Manufacturing / Supply Chain",
        domain="manufacturing",
        specialization="Aerospace manufacturing and supply chain",
        keywords=["manufacturing", "supply chain", "production", "supplier", "fabrication"],
        required_certifications=["AS9100", "Lean Six Sigma"],
        related_standards=["AS9100", "NADCAP"],
        job_role={"title": "Manufacturing Engineer", "level": "Senior"},
        education={"degree": "MS Manufacturing/Industrial Engineering"},
        skills={"items": ["Lean Manufacturing", "Quality Control", "Supply Chain Management"]},
    ),
    "operations": SubsystemProfile(
        subsystem_id="operations_sme",
        name="Operational User (Tactics)",
        domain="operations",
        specialization="Operational employment and tactics",
        keywords=["operational", "tactics", "employment", "mission", "combat"],
        required_certifications=["Weapons School", "Operational Experience"],
        related_standards=["JCIDS", "CONOPS"],
        job_role={"title": "Operational Requirements Officer", "level": "Lt Col/Colonel"},
        education={"degree": "Advanced Studies", "focus": "Military Operations"},
        skills={"items": ["Tactics Development", "Mission Planning", "Requirements Analysis"]},
    ),
    "cyber": SubsystemProfile(
        subsystem_id="cyber_sme",
        name="Cyber Operations / Mission Assurance",
        domain="cybersecurity",
        specialization="Weapon system cybersecurity and mission assurance",
        keywords=["cyber", "mission assurance", "security", "network", "protection"],
        required_certifications=["CISSP", "CAP", "RMF"],
        related_standards=["NIST 800-53", "RMF"],
        job_role={"title": "Cybersecurity Engineer", "level": "Senior"},
        education={"degree": "MS Cybersecurity/Computer Science"},
        skills={"items": ["Vulnerability Assessment", "RMF", "Secure Development"]},
    ),
    "systems_engineering": SubsystemProfile(
        subsystem_id="systems_eng_sme",
        name="Systems Engineering / Integration Lead",
        domain="systems_engineering",
        specialization="Weapon system integration and SE processes",
        keywords=["systems engineering", "integration", "interface", "architecture", "requirements"],
        required_certifications=["INCOSE CSEP"],
        related_standards=["ISO 15288", "MIL-STD-881"],
        job_role={"title": "Chief Systems Engineer", "level": "Principal"},
        education={"degree": "MS Systems Engineering"},
        skills={"items": ["MBSE", "Requirements Management", "Technical Integration"]},
    ),
}

REGULATORY_PROFILES = {
    "airworthiness": SubsystemProfile(
        subsystem_id="airworthiness_sme",
        name="Airworthiness / Safety Authority",
        domain="regulatory",
        specialization="Flight safety and airworthiness certification",
        keywords=["airworthiness", "safety", "certification", "mea", "flight"],
        required_certifications=["ASP", "Flight Safety"],
        related_standards=["MIL-HDBK-516", "SAE ARP4754"],
        job_role={"title": "Airworthiness Engineer", "level": "Senior"},
        education={"degree": "MS Aerospace Engineering"},
        skills={"items": ["Safety Analysis", "Certification", "Hazard Assessment"]},
    ),
    "export": SubsystemProfile(
        subsystem_id="export_sme",
        name="Export Controls / ITAR",
        domain="regulatory",
        specialization="Export control regulations and compliance",
        keywords=["export", "itar", "ear", "technology control", "foreign"],
        required_certifications=["Export Compliance Certification"],
        related_standards=["ITAR", "EAR"],
        job_role={"title": "Export Control Officer", "level": "Manager"},
        education={"degree": "JD/MS International Trade"},
        skills={"items": ["Export Classification", "License Applications", "TCP"]},
    ),
    "contracting": SubsystemProfile(
        subsystem_id="contracting_sme",
        name="Contracting / FAR-DFARS",
        domain="regulatory",
        specialization="Federal acquisition regulations",
        keywords=["contract", "far", "dfars", "acquisition", "proposal"],
        required_certifications=["DAU Contracting Level III"],
        related_standards=["FAR", "DFARS"],
        job_role={"title": "Contracting Officer", "level": "Senior"},
        education={"degree": "MBA/JD"},
        skills={"items": ["Contract Negotiation", "FAR/DFARS", "Cost Analysis"]},
    ),
}

COMPLIANCE_PROFILES = {
    "rmf": SubsystemProfile(
        subsystem_id="rmf_sme",
        name="Security Compliance (RMF/ATO)",
        domain="compliance",
        specialization="Risk Management Framework and authorization",
        keywords=["rmf", "ato", "authorization", "accreditation", "security"],
        required_certifications=["CISM", "CAP"],
        related_standards=["NIST 800-37", "NIST 800-53"],
        job_role={"title": "ISSO/ISSM", "level": "Senior"},
        education={"degree": "MS Cybersecurity"},
        skills={"items": ["RMF Process", "Security Controls", "POA&M Management"]},
    ),
    "quality": SubsystemProfile(
        subsystem_id="quality_sme",
        name="Quality Compliance (AS9100)",
        domain="compliance",
        specialization="Aerospace quality management systems",
        keywords=["quality", "as9100", "iso", "audit", "nonconformance"],
        required_certifications=["CQA", "Lead Auditor"],
        related_standards=["AS9100", "AS9102"],
        job_role={"title": "Quality Manager", "level": "Senior"},
        education={"degree": "MS Quality Engineering"},
        skills={"items": ["Quality Systems", "Root Cause Analysis", "Audit"]},
    ),
    "config": SubsystemProfile(
        subsystem_id="config_sme",
        name="Configuration Management / Data Gov",
        domain="compliance",
        specialization="Configuration and data management",
        keywords=["configuration", "config", "baseline", "change", "data"],
        required_certifications=["CM Certification"],
        related_standards=["MIL-STD-973", "EIA-649"],
        job_role={"title": "Configuration Manager", "level": "Senior"},
        education={"degree": "MS Engineering/IT"},
        skills={"items": ["Baseline Management", "Change Control", "Data Rights"]},
    ),
}
