from .registry import KARegistry, KAMetadata
# Import modules to register them side-effectfully
# Standardized KA Suite (114 Active KAs)
from .modules import (
    # Core Aggregates
    ka00_control_core,
    ka00_reasoning_core,
    ka10_synthesis_core,
    ka20_resolution_core,
    
    # Range 003-012
    ka03_gap_analysis,
    ka04_input_validation,
    ka09_evidence_validation,
    ka10_bias_detection,
    ka12_persona_simulation,
    
    # Range 015-030 (Already in resolution core but some might be unique files)
    ka15_temporal_reasoning,
    ka16_regulatory_mapping,
    ka18_source_provenance,
    ka22_risk_assessment,
    ka23_belief_decay,
    ka24_trust_gate,
    ka26_contradiction_detection,
    ka27_ethical_impact,
    
    # Range 031-060
    ka31_algorithm_selection,
    ka32_orchestration_controller,
    ka34_adversarial_reasoning,
    ka35_bayesian_imputation,
    ka36_pareto_optimization,
    ka37_norm_emergence,
    ka38_cross_modal_synthesis,
    ka39_ontology_drift,
    ka40_semantic_alignment,
    ka41_confidence_normalization,
    ka42_contradiction_propagation,
    ka43_knowledge_lineage,
    ka44_creative_composer,
    ka45_bias_pattern_analyzer,
    ka46_memory_patcher,
    ka47_meta_algo,
    ka48_ontological_resolver,
    ka49_redundancy_detector,
    ka50_integrity_validator,
    ka51_knowledge_distillation,
    ka52_temporal_evolution,
    ka53_knowledge_compression,
    ka54_cross_lingual_fusion,
    ka55_multimodal_integration,
    ka56_narrative_explainability,
    ka57_persona_adaptation,
    ka58_interactive_clarification,
    ka59_predictive_preemption,
    ka60_cognitive_load_balancer,
    
    # Range 061-090
    ka61_adversarial_shield,
    ka62_trust_scoring,
    ka63_performance_learning,
    ka64_failure_pattern,
    ka65_regression_tester,
    ka66_causal_inference,
    ka67_analogical_reasoning,
    ka68_domain_tuner,
    ka69_cultural_adapter,
    ka70_counterfactual_sim,
    ka71_provenance_tracker,
    ka72_context_optimizer,
    ka73_intent_clarifier,
    ka74_privacy_preserver,
    ka75_bias_mitigation,
    ka76_graph_pruner,
    ka77_importance_scorer,
    ka78_memory_tier,
    ka79_promotion_gate,
    ka80_sim_cost_estimator,
    ka81_sim_budget_enforcer,
    ka82_drift_monitor,
    ka83_revalidation_scheduler,
    ka84_consensus_engine,
    ka85_anomaly_detection,
    ka86_usage_analytics,
    ka87_explainability_coverage,
    ka88_lifecycle_manager,
    ka89_policy_tracker,
    ka90_compliance_validator,
    
    # Range 091-114
    ka91_scenario_archivist,
    ka92_dependency_auditor,
    ka93_trust_decay,
    ka94_quarantine_engine,
    ka95_hitl_escalation,
    ka96_release_manager,
    ka97_performance_optimizer,
    ka98_benchmarking,
    ka99_integrity_auditor,
    ka100_evolution_controller,
    ka101_chaos_governor,
    ka102_entropy_quantifier,
    ka103_rollback_manager,
    ka104_truth_utility,
    ka105_obsolescence_monitor,
    ka106_override_capture,
    ka107_boundary_enforcer,
    ka108_escalation_detector,
    ka109_containment_classifier,
    ka110_coupling_risk,
    ka111_goal_drift,
    ka112_introspection_auditor,
    ka113_complexity_router,
    ka114_external_research
)
