"""Frozen initial production schema

Revision ID: 000000000001
Revises:
Create Date: 2026-07-13

Generated once from the reviewed Phase 4 SQLAlchemy metadata. Do not regenerate
this revision after release; add a new forward migration instead.
"""

from alembic import op
import sqlalchemy as sa


revision = "000000000001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table('cross_store_materialization_states',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.String(length=120), nullable=False),
        sa.Column('entity_id', sa.String(length=255), nullable=False),
        sa.Column('destination', sa.String(length=32), nullable=False),
        sa.Column('schema_version', sa.String(length=80), nullable=False),
        sa.Column('source_revision', sa.String(length=255), nullable=False),
        sa.Column('observed_revision', sa.String(length=255), nullable=True),
        sa.Column('payload_sha256', sa.String(length=64), nullable=False),
        sa.Column('state', sa.String(length=24), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('safe_reason', sa.String(length=120), nullable=True),
        sa.Column('last_attempt_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_type', 'entity_id', 'destination', name='uq_cross_store_materialization_entity_destination')
        )
        op.create_index('ix_cross_store_materialization_state', 'cross_store_materialization_states', ['destination', 'state'], unique=False)
        op.create_table('cross_store_outbox_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('entity_type', sa.String(length=120), nullable=False),
        sa.Column('entity_id', sa.String(length=255), nullable=False),
        sa.Column('destination', sa.String(length=32), nullable=False),
        sa.Column('operation', sa.String(length=80), nullable=False),
        sa.Column('schema_version', sa.String(length=80), nullable=False),
        sa.Column('source_revision', sa.String(length=255), nullable=False),
        sa.Column('correlation_id', sa.String(length=128), nullable=False),
        sa.Column('payload', sa.JSON(), nullable=False),
        sa.Column('payload_sha256', sa.String(length=64), nullable=False),
        sa.Column('status', sa.String(length=24), nullable=False),
        sa.Column('attempts', sa.Integer(), nullable=False),
        sa.Column('available_at', sa.DateTime(), nullable=True),
        sa.Column('locked_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('safe_reason', sa.String(length=120), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('entity_type', 'entity_id', 'destination', 'operation', 'source_revision', name='uq_cross_store_outbox_source_delivery')
        )
        op.create_index('ix_cross_store_outbox_destination', 'cross_store_outbox_events', ['destination', 'status'], unique=False)
        op.create_index('ix_cross_store_outbox_entity', 'cross_store_outbox_events', ['entity_type', 'entity_id'], unique=False)
        op.create_index('ix_cross_store_outbox_pending', 'cross_store_outbox_events', ['status', 'available_at'], unique=False)
        op.create_table('mcp_servers',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.String(length=64), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('version', sa.String(length=32), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('protocol_version', sa.String(length=32), nullable=True),
        sa.Column('supports_resources', sa.Boolean(), nullable=True),
        sa.Column('supports_tools', sa.Boolean(), nullable=True),
        sa.Column('supports_prompts', sa.Boolean(), nullable=True),
        sa.Column('supports_logging', sa.Boolean(), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('server_metadata', sa.JSON(), nullable=True),
        sa.Column('total_requests', sa.Integer(), nullable=True),
        sa.Column('successful_requests', sa.Integer(), nullable=True),
        sa.Column('failed_requests', sa.Integer(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_active', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_mcp_servers_server_id'), 'mcp_servers', ['server_id'], unique=True)
        op.create_index(op.f('ix_mcp_servers_tenant_id'), 'mcp_servers', ['tenant_id'], unique=False)
        op.create_table('truth_link_messages',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('message_id', sa.String(length=64), nullable=False),
        sa.Column('source_module', sa.String(length=32), nullable=False),
        sa.Column('target_module', sa.String(length=32), nullable=True),
        sa.Column('message_type', sa.String(length=50), nullable=False),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('retry_count', sa.Integer(), nullable=True),
        sa.Column('max_retries', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_truth_link_messages_message_id'), 'truth_link_messages', ['message_id'], unique=True)
        op.create_index(op.f('ix_truth_link_messages_message_type'), 'truth_link_messages', ['message_type'], unique=False)
        op.create_table('ukg_domains',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_domains_tenant_id'), 'ukg_domains', ['tenant_id'], unique=False)
        op.create_table('ukg_knowledge_algorithms',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('ka_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('version', sa.String(length=20), nullable=True),
        sa.Column('config_schema', sa.JSON(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('ka_id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_knowledge_algorithms_tenant_id'), 'ukg_knowledge_algorithms', ['tenant_id'], unique=False)
        op.create_table('ukg_locations',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('location_type', sa.String(length=50), nullable=True),
        sa.Column('latitude', sa.Float(), nullable=True),
        sa.Column('longitude', sa.Float(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('parent_location_id', sa.Integer(), nullable=True),
        sa.Column('attributes', sa.JSON(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['parent_location_id'], ['ukg_locations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_locations_tenant_id'), 'ukg_locations', ['tenant_id'], unique=False)
        op.create_table('ukg_method_nodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('method_type', sa.String(length=100), nullable=False),
        sa.Column('implementation_details', sa.Text(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_method_nodes_tenant_id'), 'ukg_method_nodes', ['tenant_id'], unique=False)
        op.create_table('ukg_nodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('node_type', sa.String(length=100), nullable=False),
        sa.Column('label', sa.String(length=255), nullable=False),
        sa.Column('axis_number', sa.Integer(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('attributes', sa.JSON(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index('ix_ukg_nodes_axis_number', 'ukg_nodes', ['axis_number'], unique=False)
        op.create_index('ix_ukg_nodes_node_type', 'ukg_nodes', ['node_type'], unique=False)
        op.create_index(op.f('ix_ukg_nodes_tenant_id'), 'ukg_nodes', ['tenant_id'], unique=False)
        op.create_table('ukg_personas',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('persona_id', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('traits', sa.JSON(), nullable=True),
        sa.Column('strengths', sa.JSON(), nullable=True),
        sa.Column('focus', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('persona_id'),
        sa.UniqueConstraint('uid')
        )
        op.create_table('ukg_pillar_levels',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('pillar_id', sa.String(length=10), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('sublevels', sa.JSON(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('pillar_id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_pillar_levels_tenant_id'), 'ukg_pillar_levels', ['tenant_id'], unique=False)
        op.create_table('ukg_sectors',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('sector_code', sa.String(length=50), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('sector_code'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_sectors_tenant_id'), 'ukg_sectors', ['tenant_id'], unique=False)
        op.create_table('ukg_time_contexts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('name', sa.String(length=255), nullable=False),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_time_contexts_tenant_id'), 'ukg_time_contexts', ['tenant_id'], unique=False)
        op.create_table('users',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('username', sa.String(length=64), nullable=False),
        sa.Column('email', sa.String(length=255), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=True),
        sa.Column('sid', sa.String(length=255), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
        sa.Column('locked_until', sa.DateTime(), nullable=True),
        sa.Column('last_successful_login', sa.DateTime(), nullable=True),
        sa.Column('last_password_change', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('email'),
        sa.UniqueConstraint('sid'),
        sa.UniqueConstraint('username')
        )
        op.create_index('ix_users_active', 'users', ['active'], unique=False)
        op.create_index('ix_users_created_at', 'users', ['created_at'], unique=False)
        op.create_index('ix_users_email', 'users', ['email'], unique=False)
        op.create_index('ix_users_username', 'users', ['username'], unique=False)
        op.create_table('api_keys',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=120), nullable=False),
        sa.Column('key', sa.String(length=128), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('revoked_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_api_keys_key'), 'api_keys', ['key'], unique=True)
        op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
        op.create_table('audit_logs',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('windows_sid', sa.String(length=255), nullable=True),
        sa.Column('action', sa.String(length=100), nullable=False),
        sa.Column('details', sa.Text(), nullable=True),
        sa.Column('ip_address', sa.String(length=45), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
        op.create_table('chat_sessions',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('model', sa.String(length=100), nullable=True),
        sa.Column('mode', sa.String(length=50), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('external_api_keys',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('key_prefix', sa.String(length=12), nullable=False),
        sa.Column('key_hash', sa.String(length=256), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('total_requests', sa.Integer(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
        sa.Column('rate_limit_daily', sa.Integer(), nullable=True),
        sa.Column('max_tokens_per_request', sa.Integer(), nullable=True),
        sa.Column('permissions', sa.JSON(), nullable=True),
        sa.Column('allowed_providers', sa.JSON(), nullable=True),
        sa.Column('allowed_models', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('expires_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('feature_flag_audit_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('flag_key', sa.String(length=120), nullable=False),
        sa.Column('old_value', sa.Boolean(), nullable=True),
        sa.Column('new_value', sa.Boolean(), nullable=True),
        sa.Column('actor_id', sa.Integer(), nullable=True),
        sa.Column('actor_username', sa.String(length=120), nullable=True),
        sa.Column('change_reason', sa.Text(), nullable=True),
        sa.Column('source', sa.String(length=30), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_feature_flag_audit_actor', 'feature_flag_audit_events', ['actor_id'], unique=False)
        op.create_index('ix_feature_flag_audit_key', 'feature_flag_audit_events', ['flag_key'], unique=False)
        op.create_table('feature_flags',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('flag_key', sa.String(length=120), nullable=False),
        sa.Column('value', sa.Boolean(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('rollout_percentage', sa.Integer(), nullable=False),
        sa.Column('target_roles', sa.JSON(), nullable=True),
        sa.Column('is_locked', sa.Boolean(), nullable=False),
        sa.Column('updated_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_feature_flags_key', 'feature_flags', ['flag_key'], unique=True)
        op.create_table('llm_providers',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('provider_type', sa.String(length=50), nullable=False),
        sa.Column('api_key_encrypted', sa.LargeBinary(), nullable=True),
        sa.Column('endpoint', sa.String(length=500), nullable=True),
        sa.Column('model_id', sa.String(length=100), nullable=True),
        sa.Column('deployment_name', sa.String(length=100), nullable=True),
        sa.Column('api_version', sa.String(length=20), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('is_default', sa.Boolean(), nullable=True),
        sa.Column('priority', sa.Integer(), nullable=True),
        sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
        sa.Column('rate_limit_tpm', sa.Integer(), nullable=True),
        sa.Column('timeout_seconds', sa.Integer(), nullable=True),
        sa.Column('max_retries', sa.Integer(), nullable=True),
        sa.Column('config', sa.JSON(), nullable=True),
        sa.Column('tenant_id', sa.String(length=100), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('last_used_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('mcp_prompts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('arguments', sa.JSON(), nullable=True),
        sa.Column('prompt_metadata', sa.JSON(), nullable=True),
        sa.Column('usage_count', sa.Integer(), nullable=True),
        sa.Column('last_used', sa.DateTime(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_mcp_prompts_name'), 'mcp_prompts', ['name'], unique=False)
        op.create_index(op.f('ix_mcp_prompts_tenant_id'), 'mcp_prompts', ['tenant_id'], unique=False)
        op.create_table('mcp_resources',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('uri', sa.String(length=256), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('mime_type', sa.String(length=64), nullable=True),
        sa.Column('resource_metadata', sa.JSON(), nullable=True),
        sa.Column('access_count', sa.Integer(), nullable=True),
        sa.Column('last_accessed', sa.DateTime(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_mcp_resources_tenant_id'), 'mcp_resources', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_mcp_resources_uri'), 'mcp_resources', ['uri'], unique=False)
        op.create_table('mcp_tools',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('server_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=128), nullable=False),
        sa.Column('description', sa.Text(), nullable=False),
        sa.Column('input_schema', sa.JSON(), nullable=False),
        sa.Column('tool_metadata', sa.JSON(), nullable=True),
        sa.Column('execution_count', sa.Integer(), nullable=True),
        sa.Column('success_count', sa.Integer(), nullable=True),
        sa.Column('failure_count', sa.Integer(), nullable=True),
        sa.Column('last_executed', sa.DateTime(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['server_id'], ['mcp_servers.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_mcp_tools_name'), 'mcp_tools', ['name'], unique=False)
        op.create_index(op.f('ix_mcp_tools_tenant_id'), 'mcp_tools', ['tenant_id'], unique=False)
        op.create_table('model_routing_policies',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('policy_name', sa.String(length=120), nullable=False),
        sa.Column('version', sa.String(length=40), nullable=False),
        sa.Column('rules', sa.JSON(), nullable=False),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_model_routing_policy_active', 'model_routing_policies', ['is_active'], unique=False)
        op.create_index('ix_model_routing_policy_name', 'model_routing_policies', ['policy_name'], unique=False)
        op.create_index('ix_model_routing_policy_name_version', 'model_routing_policies', ['policy_name', 'version'], unique=True)
        op.create_table('password_history',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('password_hash', sa.String(length=256), nullable=False),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_password_history_user_id'), 'password_history', ['user_id'], unique=False)
        op.create_table('prompt_templates',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('template_key', sa.String(length=120), nullable=False),
        sa.Column('version', sa.String(length=40), nullable=False),
        sa.Column('template_body', sa.Text(), nullable=False),
        sa.Column('description', sa.String(length=255), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('is_active', sa.Boolean(), nullable=True),
        sa.Column('approval_state', sa.String(length=30), nullable=False),
        sa.Column('approved_by', sa.Integer(), nullable=True),
        sa.Column('approved_at', sa.DateTime(), nullable=True),
        sa.Column('rejected_reason', sa.Text(), nullable=True),
        sa.Column('submitted_for_review_at', sa.DateTime(), nullable=True),
        sa.Column('created_by', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['approved_by'], ['users.id'], ),
        sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_prompt_templates_active', 'prompt_templates', ['is_active'], unique=False)
        op.create_index('ix_prompt_templates_approval', 'prompt_templates', ['approval_state'], unique=False)
        op.create_index('ix_prompt_templates_key', 'prompt_templates', ['template_key'], unique=False)
        op.create_index('ix_prompt_templates_key_version', 'prompt_templates', ['template_key', 'version'], unique=True)
        op.create_table('simulation_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=36), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('parameters', sa.JSON(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('current_step', sa.Integer(), nullable=True),
        sa.Column('total_steps', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('results', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('session_id')
        )
        op.create_index('ix_simulation_sessions_created_at', 'simulation_sessions', ['created_at'], unique=False)
        op.create_index('ix_simulation_sessions_status', 'simulation_sessions', ['status'], unique=False)
        op.create_index('ix_simulation_sessions_user_id', 'simulation_sessions', ['user_id'], unique=False)
        op.create_index('ix_simulation_sessions_user_status', 'simulation_sessions', ['user_id', 'status'], unique=False)
        op.create_table('trace_runs',
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=True),
        sa.Column('tenant_id', sa.String(length=100), nullable=True),
        sa.Column('workspace_id', sa.String(length=100), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('correlation_id', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.Column('model_name', sa.String(length=100), nullable=True),
        sa.Column('model_version', sa.String(length=50), nullable=True),
        sa.Column('policy_pack_id', sa.String(length=100), nullable=True),
        sa.Column('policy_pack_version', sa.String(length=50), nullable=True),
        sa.Column('data_snapshot', sa.JSON(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('entropy', sa.Float(), nullable=True),
        sa.Column('bias_risk', sa.Float(), nullable=True),
        sa.Column('input_message', sa.Text(), nullable=True),
        sa.Column('final_answer', sa.Text(), nullable=True),
        sa.Column('tier', sa.String(length=10), nullable=True),
        sa.Column('coordinate17_id', sa.UUID(), nullable=True),
        sa.Column('evidence_pack_hash', sa.String(length=64), nullable=True),
        sa.Column('layers_executed', sa.JSON(), nullable=True),
        sa.Column('refinement_cycles', sa.Integer(), nullable=True),
        sa.Column('regulatory_pass', sa.Boolean(), nullable=True),
        sa.Column('security_pass', sa.Boolean(), nullable=True),
        sa.Column('truthgate_decision', sa.String(length=16), nullable=True),
        sa.Column('token_cost', sa.Integer(), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('frost_depth', sa.Integer(), nullable=True),
        sa.Column('truth_engine_mode', sa.String(length=50), nullable=True),
        sa.ForeignKeyConstraint(['coordinate17_id'], ['trace_axis_vectors.vector_id'], name='fk_trace_runs_axis_vector', use_alter=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('run_id')
        )
        op.create_index('ix_trace_runs_created_at', 'trace_runs', ['created_at'], unique=False)
        op.create_index('ix_trace_runs_session_id', 'trace_runs', ['session_id'], unique=False)
        op.create_index('ix_trace_runs_status', 'trace_runs', ['status'], unique=False)
        op.create_index('ix_trace_runs_user_id', 'trace_runs', ['user_id'], unique=False)
        op.create_table('truth_budgets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('tenant_id', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('budget_limit', sa.Float(), nullable=True),
        sa.Column('budget_spent', sa.Float(), nullable=True),
        sa.Column('budget_period', sa.String(length=20), nullable=True),
        sa.Column('kill_switch_triggered', sa.Boolean(), nullable=True),
        sa.Column('kill_switch_threshold', sa.Float(), nullable=True),
        sa.Column('downgrade_tier', sa.String(length=20), nullable=True),
        sa.Column('tier_limits', sa.JSON(), nullable=True),
        sa.Column('alerts_enabled', sa.Boolean(), nullable=True),
        sa.Column('alert_thresholds', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('reset_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_truth_budgets_tenant_id'), 'truth_budgets', ['tenant_id'], unique=True)
        op.create_table('truth_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('tier', sa.String(length=20), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('query', sa.Text(), nullable=True),
        sa.Column('input_embedding', sa.Text(), nullable=True),
        sa.Column('response', sa.Text(), nullable=True),
        sa.Column('budget_limit', sa.Float(), nullable=True),
        sa.Column('budget_spent', sa.Float(), nullable=True),
        sa.Column('token_count', sa.Integer(), nullable=True),
        sa.Column('confidence_score', sa.Float(), nullable=True),
        sa.Column('safety_score', sa.Float(), nullable=True),
        sa.Column('llm_model', sa.String(length=64), nullable=True),
        sa.Column('routing_profile', sa.String(length=32), nullable=True),
        sa.Column('personas_used', sa.JSON(), nullable=True),
        sa.Column('axis_context', sa.JSON(), nullable=True),
        sa.Column('workflow_steps', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_truth_sessions_session_id'), 'truth_sessions', ['session_id'], unique=True)
        op.create_index(op.f('ix_truth_sessions_tenant_id'), 'truth_sessions', ['tenant_id'], unique=False)
        op.create_table('ukg_edges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('edge_type', sa.String(length=100), nullable=False),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('source_node_id', sa.Integer(), nullable=False),
        sa.Column('target_node_id', sa.Integer(), nullable=False),
        sa.Column('attributes', sa.JSON(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.Column('active', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['source_node_id'], ['ukg_nodes.id'], ),
        sa.ForeignKeyConstraint(['target_node_id'], ['ukg_nodes.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index('ix_ukg_edges_edge_type', 'ukg_edges', ['edge_type'], unique=False)
        op.create_index(op.f('ix_ukg_edges_tenant_id'), 'ukg_edges', ['tenant_id'], unique=False)
        op.create_table('ukg_ka_executions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('ka_id', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('input_data', sa.JSON(), nullable=True),
        sa.Column('output_data', sa.JSON(), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('execution_time_ms', sa.Integer(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['ka_id'], ['ukg_knowledge_algorithms.ka_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index(op.f('ix_ukg_ka_executions_tenant_id'), 'ukg_ka_executions', ['tenant_id'], unique=False)
        op.create_table('ukg_knowledge_nodes',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('node_id', sa.String(length=50), nullable=True),
        sa.Column('node_type', sa.String(length=50), nullable=True),
        sa.Column('label', sa.String(length=100), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('axis_number', sa.Integer(), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('uid', sa.String(length=255), nullable=True),
        sa.Column('title', sa.String(length=255), nullable=True),
        sa.Column('content', sa.Text(), nullable=True),
        sa.Column('content_type', sa.String(length=50), nullable=True),
        sa.Column('pillar_level_id', sa.Integer(), nullable=True),
        sa.Column('domain_id', sa.Integer(), nullable=True),
        sa.Column('location_id', sa.Integer(), nullable=True),
        sa.Column('time_context_id', sa.Integer(), nullable=True),
        sa.Column('node_metadata', sa.JSON(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['domain_id'], ['ukg_domains.id'], ),
        sa.ForeignKeyConstraint(['location_id'], ['ukg_locations.id'], ),
        sa.ForeignKeyConstraint(['pillar_level_id'], ['ukg_pillar_levels.id'], ),
        sa.ForeignKeyConstraint(['time_context_id'], ['ukg_time_contexts.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('node_id'),
        sa.UniqueConstraint('uid')
        )
        op.create_index('ix_ukg_knowledge_nodes_axis_number', 'ukg_knowledge_nodes', ['axis_number'], unique=False)
        op.create_index('ix_ukg_knowledge_nodes_node_type', 'ukg_knowledge_nodes', ['node_type'], unique=False)
        op.create_index('ix_ukg_knowledge_nodes_tenant_id', 'ukg_knowledge_nodes', ['tenant_id'], unique=False)
        op.create_index('ix_ukg_knowledge_nodes_type_axis', 'ukg_knowledge_nodes', ['node_type', 'axis_number'], unique=False)
        op.create_table('ukg_sessions',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('user_query', sa.Text(), nullable=True),
        sa.Column('target_confidence', sa.Float(), nullable=True),
        sa.Column('final_confidence', sa.Float(), nullable=True),
        sa.Column('status', sa.String(length=50), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('started_at', sa.DateTime(), nullable=True),
        sa.Column('completed_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_ukg_sessions_session_id'), 'ukg_sessions', ['session_id'], unique=True)
        op.create_index(op.f('ix_ukg_sessions_tenant_id'), 'ukg_sessions', ['tenant_id'], unique=False)
        op.create_table('user_ai_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('preferred_provider', sa.String(length=64), nullable=True),
        sa.Column('preferred_model', sa.String(length=128), nullable=True),
        sa.Column('ai_processing_enabled', sa.Boolean(), nullable=False),
        sa.Column('store_chat_history', sa.Boolean(), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_ai_preferences_user_id'), 'user_ai_preferences', ['user_id'], unique=True)
        op.create_table('user_notification_preferences',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=False),
        sa.Column('email_on_run_complete', sa.Boolean(), nullable=False),
        sa.Column('email_on_run_failed', sa.Boolean(), nullable=False),
        sa.Column('email_on_simulation_complete', sa.Boolean(), nullable=False),
        sa.Column('inapp_run_complete', sa.Boolean(), nullable=False),
        sa.Column('inapp_run_failed', sa.Boolean(), nullable=False),
        sa.Column('inapp_simulation_complete', sa.Boolean(), nullable=False),
        sa.Column('inapp_system_alerts', sa.Boolean(), nullable=False),
        sa.Column('digest_frequency', sa.String(length=20), nullable=False),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_user_notification_preferences_user_id'), 'user_notification_preferences', ['user_id'], unique=True)
        op.create_table('ai_audit_events',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('api_key_id', sa.UUID(), nullable=True),
        sa.Column('provider', sa.String(length=100), nullable=True),
        sa.Column('model', sa.String(length=120), nullable=False),
        sa.Column('model_version', sa.String(length=60), nullable=False),
        sa.Column('prompt_template_key', sa.String(length=120), nullable=True),
        sa.Column('prompt_template_version', sa.String(length=40), nullable=True),
        sa.Column('routing_policy_name', sa.String(length=120), nullable=True),
        sa.Column('routing_policy_version', sa.String(length=40), nullable=True),
        sa.Column('classification', sa.JSON(), nullable=True),
        sa.Column('governance_flags', sa.JSON(), nullable=True),
        sa.Column('request_tokens_estimate', sa.Integer(), nullable=True),
        sa.Column('tokens_in', sa.Integer(), nullable=True),
        sa.Column('tokens_out', sa.Integer(), nullable=True),
        sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_code', sa.String(length=100), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('metadata', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['api_key_id'], ['external_api_keys.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index('ix_ai_audit_created_at', 'ai_audit_events', ['created_at'], unique=False)
        op.create_index('ix_ai_audit_model', 'ai_audit_events', ['model'], unique=False)
        op.create_index('ix_ai_audit_run_id', 'ai_audit_events', ['run_id'], unique=False)
        op.create_table('chat_messages',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('session_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=False),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=True),
        sa.Column('is_enhanced', sa.Boolean(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('compliance_mappings',
        sa.Column('mapping_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('framework', sa.String(length=50), nullable=False),
        sa.Column('control_id', sa.String(length=100), nullable=False),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('evidence_refs', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('mapping_id')
        )
        op.create_table('llm_provider_usage',
        sa.Column('id', sa.UUID(), nullable=False),
        sa.Column('provider_id', sa.UUID(), nullable=False),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('api_key_id', sa.UUID(), nullable=True),
        sa.Column('run_id', sa.UUID(), nullable=True),
        sa.Column('model', sa.String(length=100), nullable=True),
        sa.Column('tokens_in', sa.Integer(), nullable=True),
        sa.Column('tokens_out', sa.Integer(), nullable=True),
        sa.Column('latency_ms', sa.Integer(), nullable=True),
        sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
        sa.Column('success', sa.Boolean(), nullable=True),
        sa.Column('error_code', sa.String(length=100), nullable=True),
        sa.Column('error_message', sa.Text(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['api_key_id'], ['external_api_keys.id'], ),
        sa.ForeignKeyConstraint(['provider_id'], ['llm_providers.id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('memory_entries',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('session_id', sa.String(length=255), nullable=False),
        sa.Column('entry_type', sa.String(length=100), nullable=False),
        sa.Column('pass_num', sa.Integer(), nullable=True),
        sa.Column('layer_num', sa.Integer(), nullable=True),
        sa.Column('content', sa.JSON(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('tenant_id', sa.String(length=64), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['ukg_sessions.session_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_memory_entries_entry_type'), 'memory_entries', ['entry_type'], unique=False)
        op.create_index(op.f('ix_memory_entries_tenant_id'), 'memory_entries', ['tenant_id'], unique=False)
        op.create_index(op.f('ix_memory_entries_uid'), 'memory_entries', ['uid'], unique=True)
        op.create_table('trace_axis_vectors',
        sa.Column('vector_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('axes', sa.JSON(), nullable=False),
        sa.Column('coordinate_hash', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('vector_id'),
        sa.UniqueConstraint('run_id')
        )
        op.create_table('trace_claims',
        sa.Column('claim_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('text', sa.Text(), nullable=False),
        sa.Column('answer_span_start', sa.Integer(), nullable=True),
        sa.Column('answer_span_end', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('evidence_ids', sa.JSON(), nullable=True),
        sa.Column('stage_ids', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('claim_id')
        )
        op.create_table('trace_evidence',
        sa.Column('evidence_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('source_type', sa.String(length=50), nullable=True),
        sa.Column('source_id', sa.String(length=255), nullable=True),
        sa.Column('source_title', sa.String(length=500), nullable=True),
        sa.Column('authority', sa.String(length=20), nullable=True),
        sa.Column('locator', sa.JSON(), nullable=True),
        sa.Column('snippet', sa.Text(), nullable=True),
        sa.Column('content_hash', sa.String(length=100), nullable=True),
        sa.Column('retrieval_method', sa.String(length=50), nullable=True),
        sa.Column('relevance_score', sa.Float(), nullable=True),
        sa.Column('axis_match_score', sa.Float(), nullable=True),
        sa.Column('used_by_claims', sa.JSON(), nullable=True),
        sa.Column('used_by_personas', sa.JSON(), nullable=True),
        sa.Column('used_by_stages', sa.JSON(), nullable=True),
        sa.Column('conflicts_with', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('evidence_id')
        )
        op.create_index('ix_trace_evidence_run_id', 'trace_evidence', ['run_id'], unique=False)
        op.create_index('ix_trace_evidence_source_type', 'trace_evidence', ['source_type'], unique=False)
        op.create_table('trace_exports',
        sa.Column('export_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('format', sa.String(length=20), nullable=True),
        sa.Column('destination', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('exported_at', sa.DateTime(), nullable=True),
        sa.Column('user_id', sa.Integer(), nullable=True),
        sa.Column('bundle_ref', sa.String(length=512), nullable=True),
        sa.Column('manifest_hash', sa.String(length=128), nullable=True),
        sa.Column('file_size_bytes', sa.Integer(), nullable=True),
        sa.Column('payload', sa.JSON(), nullable=True),
        sa.Column('options', sa.JSON(), nullable=True),
        sa.Column('encrypted', sa.Boolean(), nullable=True),
        sa.Column('signed', sa.Boolean(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
        sa.PrimaryKeyConstraint('export_id')
        )
        op.create_table('trace_memory_events',
        sa.Column('event_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('memory_type', sa.String(length=20), nullable=True),
        sa.Column('content', sa.JSON(), nullable=False),
        sa.Column('context_keys', sa.JSON(), nullable=True),
        sa.Column('impact_score', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('event_id')
        )
        op.create_table('trace_personas',
        sa.Column('persona_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('persona_type', sa.String(length=50), nullable=False),
        sa.Column('persona_name', sa.String(length=100), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('evidence_ids', sa.JSON(), nullable=True),
        sa.Column('context_scope', sa.Text(), nullable=True),
        sa.Column('draft_text', sa.Text(), nullable=True),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('objections', sa.JSON(), nullable=True),
        sa.Column('consensus_impact', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('persona_id')
        )
        op.create_table('trace_spans',
        sa.Column('span_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('parent_id', sa.UUID(), nullable=True),
        sa.Column('name', sa.String(length=200), nullable=False),
        sa.Column('service', sa.String(length=100), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=False),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('span_id')
        )
        op.create_table('trace_stages',
        sa.Column('stage_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('stage_type', sa.String(length=20), nullable=True),
        sa.Column('layer_index', sa.Integer(), nullable=True),
        sa.Column('step_index', sa.Integer(), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('start_time', sa.DateTime(), nullable=True),
        sa.Column('end_time', sa.DateTime(), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('inputs', sa.JSON(), nullable=True),
        sa.Column('outputs', sa.JSON(), nullable=True),
        sa.Column('decisions', sa.JSON(), nullable=True),
        sa.Column('metrics', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('stage_id')
        )
        op.create_index('ix_trace_stages_layer_index', 'trace_stages', ['layer_index'], unique=False)
        op.create_index('ix_trace_stages_run_id', 'trace_stages', ['run_id'], unique=False)
        op.create_index('ix_trace_stages_step_index', 'trace_stages', ['step_index'], unique=False)
        op.create_table('truth_artifacts',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('artifact_id', sa.String(length=64), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=True),
        sa.Column('artifact_type', sa.String(length=50), nullable=False),
        sa.Column('artifact_name', sa.String(length=256), nullable=True),
        sa.Column('content', sa.JSON(), nullable=True),
        sa.Column('content_hash', sa.String(length=64), nullable=True),
        sa.Column('file_path', sa.String(length=512), nullable=True),
        sa.Column('file_size', sa.Integer(), nullable=True),
        sa.Column('mime_type', sa.String(length=128), nullable=True),
        sa.Column('artifact_metadata', sa.JSON(), nullable=True),
        sa.Column('tags', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('retention_until', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['truth_sessions.session_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_truth_artifacts_artifact_id'), 'truth_artifacts', ['artifact_id'], unique=True)
        op.create_index(op.f('ix_truth_artifacts_session_id'), 'truth_artifacts', ['session_id'], unique=False)
        op.create_table('truth_audit_events',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('event_id', sa.String(length=64), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=True),
        sa.Column('event_type', sa.String(length=50), nullable=False),
        sa.Column('event_category', sa.String(length=50), nullable=True),
        sa.Column('event_data', sa.JSON(), nullable=True),
        sa.Column('decision_rationale', sa.Text(), nullable=True),
        sa.Column('object_store_bucket', sa.String(length=128), nullable=True),
        sa.Column('object_store_key', sa.String(length=512), nullable=True),
        sa.Column('merkle_root', sa.String(length=64), nullable=True),
        sa.Column('blockchain_anchor_tx', sa.String(length=128), nullable=True),
        sa.Column('blockchain_anchor_status', sa.String(length=32), nullable=True),
        sa.Column('hash_chain', sa.String(length=64), nullable=False),
        sa.Column('previous_hash', sa.String(length=64), nullable=True),
        sa.Column('actor_id', sa.String(length=64), nullable=True),
        sa.Column('actor_type', sa.String(length=32), nullable=True),
        sa.Column('axis_involved', sa.JSON(), nullable=True),
        sa.Column('compliance_flags', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('retention_until', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['truth_sessions.session_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_truth_audit_events_event_id'), 'truth_audit_events', ['event_id'], unique=True)
        op.create_index(op.f('ix_truth_audit_events_event_type'), 'truth_audit_events', ['event_type'], unique=False)
        op.create_index(op.f('ix_truth_audit_events_merkle_root'), 'truth_audit_events', ['merkle_root'], unique=False)
        op.create_index(op.f('ix_truth_audit_events_object_store_key'), 'truth_audit_events', ['object_store_key'], unique=False)
        op.create_index(op.f('ix_truth_audit_events_session_id'), 'truth_audit_events', ['session_id'], unique=False)
        op.create_index(op.f('ix_truth_audit_events_timestamp'), 'truth_audit_events', ['timestamp'], unique=False)
        op.create_table('truth_metrics',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('metric_id', sa.String(length=64), nullable=False),
        sa.Column('session_id', sa.String(length=64), nullable=True),
        sa.Column('metric_name', sa.String(length=128), nullable=False),
        sa.Column('metric_value', sa.Float(), nullable=False),
        sa.Column('metric_unit', sa.String(length=32), nullable=True),
        sa.Column('metric_type', sa.String(length=32), nullable=True),
        sa.Column('tier', sa.String(length=20), nullable=True),
        sa.Column('llm_model', sa.String(length=64), nullable=True),
        sa.Column('labels', sa.JSON(), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['session_id'], ['truth_sessions.session_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_index(op.f('ix_truth_metrics_metric_id'), 'truth_metrics', ['metric_id'], unique=True)
        op.create_index(op.f('ix_truth_metrics_metric_name'), 'truth_metrics', ['metric_name'], unique=False)
        op.create_index(op.f('ix_truth_metrics_session_id'), 'truth_metrics', ['session_id'], unique=False)
        op.create_index(op.f('ix_truth_metrics_timestamp'), 'truth_metrics', ['timestamp'], unique=False)
        op.create_table('ukg_integrated_views',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('knowledge_node_id', sa.Integer(), nullable=False),
        sa.Column('synthesis_method', sa.String(length=100), nullable=False),
        sa.Column('key_insights', sa.JSON(), nullable=True),
        sa.Column('comprehensive_strengths', sa.JSON(), nullable=True),
        sa.Column('potential_limitations', sa.JSON(), nullable=True),
        sa.Column('balanced_recommendations', sa.JSON(), nullable=True),
        sa.Column('perspectives', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['knowledge_node_id'], ['ukg_knowledge_nodes.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_table('ukg_knowledge_edges',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('edge_id', sa.String(length=50), nullable=False),
        sa.Column('source_node_id', sa.String(length=50), nullable=False),
        sa.Column('target_node_id', sa.String(length=50), nullable=False),
        sa.Column('edge_type', sa.String(length=50), nullable=True),
        sa.Column('weight', sa.Float(), nullable=True),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['source_node_id'], ['ukg_knowledge_nodes.node_id'], ),
        sa.ForeignKeyConstraint(['target_node_id'], ['ukg_knowledge_nodes.node_id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('edge_id')
        )
        op.create_index('ix_ukg_knowledge_edges_edge_type', 'ukg_knowledge_edges', ['edge_type'], unique=False)
        op.create_index('ix_ukg_knowledge_edges_source_node_id', 'ukg_knowledge_edges', ['source_node_id'], unique=False)
        op.create_index('ix_ukg_knowledge_edges_source_target', 'ukg_knowledge_edges', ['source_node_id', 'target_node_id'], unique=False)
        op.create_index('ix_ukg_knowledge_edges_target_node_id', 'ukg_knowledge_edges', ['target_node_id'], unique=False)
        op.create_table('ukg_perspectives',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('uid', sa.String(length=255), nullable=False),
        sa.Column('persona_id', sa.Integer(), nullable=False),
        sa.Column('knowledge_node_id', sa.Integer(), nullable=False),
        sa.Column('key_insights', sa.JSON(), nullable=True),
        sa.Column('strengths_identified', sa.JSON(), nullable=True),
        sa.Column('blind_spots', sa.JSON(), nullable=True),
        sa.Column('recommendations', sa.JSON(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.Column('updated_at', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['knowledge_node_id'], ['ukg_knowledge_nodes.id'], ),
        sa.ForeignKeyConstraint(['persona_id'], ['ukg_personas.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('uid')
        )
        op.create_table('claim_evidence_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('claim_id', sa.UUID(), nullable=False),
        sa.Column('evidence_id', sa.UUID(), nullable=False),
        sa.Column('confidence', sa.Float(), nullable=True),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(['claim_id'], ['trace_claims.claim_id'], ),
        sa.ForeignKeyConstraint(['evidence_id'], ['trace_evidence.evidence_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('evidence_conflicts',
        sa.Column('conflict_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('evidence_a_id', sa.UUID(), nullable=False),
        sa.Column('evidence_b_id', sa.UUID(), nullable=False),
        sa.Column('conflict_type', sa.String(length=50), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('resolution', sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(['evidence_a_id'], ['trace_evidence.evidence_id'], ),
        sa.ForeignKeyConstraint(['evidence_b_id'], ['trace_evidence.evidence_id'], ),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.PrimaryKeyConstraint('conflict_id')
        )
        op.create_table('persona_evidence_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('persona_id', sa.UUID(), nullable=False),
        sa.Column('evidence_id', sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(['evidence_id'], ['trace_evidence.evidence_id'], ),
        sa.ForeignKeyConstraint(['persona_id'], ['trace_personas.persona_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('trace_artifacts',
        sa.Column('artifact_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('stage_id', sa.UUID(), nullable=True),
        sa.Column('label', sa.String(length=100), nullable=False),
        sa.Column('artifact_type', sa.String(length=50), nullable=True),
        sa.Column('media_type', sa.String(length=100), nullable=True),
        sa.Column('content', sa.Text(), nullable=False),
        sa.Column('version', sa.Integer(), nullable=True),
        sa.Column('is_redacted', sa.Boolean(), nullable=True),
        sa.Column('redaction_level', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.ForeignKeyConstraint(['stage_id'], ['trace_stages.stage_id'], ),
        sa.PrimaryKeyConstraint('artifact_id')
        )
        op.create_table('trace_ka_invocations',
        sa.Column('invocation_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('stage_id', sa.UUID(), nullable=True),
        sa.Column('ka_id', sa.String(length=100), nullable=False),
        sa.Column('ka_name', sa.String(length=200), nullable=True),
        sa.Column('ka_version', sa.String(length=50), nullable=True),
        sa.Column('status', sa.String(length=20), nullable=True),
        sa.Column('duration_ms', sa.Integer(), nullable=True),
        sa.Column('inputs', sa.JSON(), nullable=True),
        sa.Column('outputs', sa.JSON(), nullable=True),
        sa.Column('routing', sa.JSON(), nullable=True),
        sa.Column('side_effects', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.ForeignKeyConstraint(['stage_id'], ['trace_stages.stage_id'], ),
        sa.PrimaryKeyConstraint('invocation_id')
        )
        op.create_table('trace_policy_decisions',
        sa.Column('decision_id', sa.UUID(), nullable=False),
        sa.Column('run_id', sa.UUID(), nullable=False),
        sa.Column('stage_id', sa.UUID(), nullable=True),
        sa.Column('policy_id', sa.String(length=100), nullable=False),
        sa.Column('policy_name', sa.String(length=200), nullable=True),
        sa.Column('rule_id', sa.String(length=100), nullable=True),
        sa.Column('decision', sa.String(length=20), nullable=False),
        sa.Column('rationale', sa.Text(), nullable=True),
        sa.Column('sensitivity_score', sa.Float(), nullable=True),
        sa.Column('modifications', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['run_id'], ['trace_runs.run_id'], ),
        sa.ForeignKeyConstraint(['stage_id'], ['trace_stages.stage_id'], ),
        sa.PrimaryKeyConstraint('decision_id')
        )
        op.create_table('trace_stage_logs',
        sa.Column('log_id', sa.Integer(), nullable=False),
        sa.Column('stage_id', sa.UUID(), nullable=False),
        sa.Column('level', sa.String(length=20), nullable=True),
        sa.Column('message', sa.Text(), nullable=False),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.Column('extra', sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(['stage_id'], ['trace_stages.stage_id'], ),
        sa.PrimaryKeyConstraint('log_id')
        )
        op.create_table('artifact_redactions',
        sa.Column('redaction_id', sa.UUID(), nullable=False),
        sa.Column('artifact_id', sa.UUID(), nullable=False),
        sa.Column('rule_id', sa.String(length=100), nullable=True),
        sa.Column('redactor_name', sa.String(length=100), nullable=True),
        sa.Column('pattern_matched', sa.String(length=255), nullable=True),
        sa.Column('timestamp', sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(['artifact_id'], ['trace_artifacts.artifact_id'], ),
        sa.PrimaryKeyConstraint('redaction_id')
        )
        op.create_table('ka_artifact_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('invocation_id', sa.UUID(), nullable=False),
        sa.Column('artifact_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['artifact_id'], ['trace_artifacts.artifact_id'], ),
        sa.ForeignKeyConstraint(['invocation_id'], ['trace_ka_invocations.invocation_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        op.create_table('stage_artifact_links',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('stage_id', sa.UUID(), nullable=False),
        sa.Column('artifact_id', sa.UUID(), nullable=False),
        sa.Column('role', sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(['artifact_id'], ['trace_artifacts.artifact_id'], ),
        sa.ForeignKeyConstraint(['stage_id'], ['trace_stages.stage_id'], ),
        sa.PrimaryKeyConstraint('id')
        )
        # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.drop_table('stage_artifact_links')
        op.drop_table('ka_artifact_links')
        op.drop_table('artifact_redactions')
        op.drop_table('trace_stage_logs')
        op.drop_table('trace_policy_decisions')
        op.drop_table('trace_ka_invocations')
        op.drop_table('trace_artifacts')
        op.drop_table('persona_evidence_links')
        op.drop_table('evidence_conflicts')
        op.drop_table('claim_evidence_links')
        op.drop_table('ukg_perspectives')
        op.drop_index('ix_ukg_knowledge_edges_target_node_id', table_name='ukg_knowledge_edges')
        op.drop_index('ix_ukg_knowledge_edges_source_target', table_name='ukg_knowledge_edges')
        op.drop_index('ix_ukg_knowledge_edges_source_node_id', table_name='ukg_knowledge_edges')
        op.drop_index('ix_ukg_knowledge_edges_edge_type', table_name='ukg_knowledge_edges')
        op.drop_table('ukg_knowledge_edges')
        op.drop_table('ukg_integrated_views')
        op.drop_index(op.f('ix_truth_metrics_timestamp'), table_name='truth_metrics')
        op.drop_index(op.f('ix_truth_metrics_session_id'), table_name='truth_metrics')
        op.drop_index(op.f('ix_truth_metrics_metric_name'), table_name='truth_metrics')
        op.drop_index(op.f('ix_truth_metrics_metric_id'), table_name='truth_metrics')
        op.drop_table('truth_metrics')
        op.drop_index(op.f('ix_truth_audit_events_timestamp'), table_name='truth_audit_events')
        op.drop_index(op.f('ix_truth_audit_events_session_id'), table_name='truth_audit_events')
        op.drop_index(op.f('ix_truth_audit_events_object_store_key'), table_name='truth_audit_events')
        op.drop_index(op.f('ix_truth_audit_events_merkle_root'), table_name='truth_audit_events')
        op.drop_index(op.f('ix_truth_audit_events_event_type'), table_name='truth_audit_events')
        op.drop_index(op.f('ix_truth_audit_events_event_id'), table_name='truth_audit_events')
        op.drop_table('truth_audit_events')
        op.drop_index(op.f('ix_truth_artifacts_session_id'), table_name='truth_artifacts')
        op.drop_index(op.f('ix_truth_artifacts_artifact_id'), table_name='truth_artifacts')
        op.drop_table('truth_artifacts')
        op.drop_index('ix_trace_stages_step_index', table_name='trace_stages')
        op.drop_index('ix_trace_stages_run_id', table_name='trace_stages')
        op.drop_index('ix_trace_stages_layer_index', table_name='trace_stages')
        op.drop_table('trace_stages')
        op.drop_table('trace_spans')
        op.drop_table('trace_personas')
        op.drop_table('trace_memory_events')
        op.drop_table('trace_exports')
        op.drop_index('ix_trace_evidence_source_type', table_name='trace_evidence')
        op.drop_index('ix_trace_evidence_run_id', table_name='trace_evidence')
        op.drop_table('trace_evidence')
        op.drop_table('trace_claims')
        op.drop_table('trace_axis_vectors')
        op.drop_index(op.f('ix_memory_entries_uid'), table_name='memory_entries')
        op.drop_index(op.f('ix_memory_entries_tenant_id'), table_name='memory_entries')
        op.drop_index(op.f('ix_memory_entries_entry_type'), table_name='memory_entries')
        op.drop_table('memory_entries')
        op.drop_table('llm_provider_usage')
        op.drop_table('compliance_mappings')
        op.drop_table('chat_messages')
        op.drop_index('ix_ai_audit_run_id', table_name='ai_audit_events')
        op.drop_index('ix_ai_audit_model', table_name='ai_audit_events')
        op.drop_index('ix_ai_audit_created_at', table_name='ai_audit_events')
        op.drop_table('ai_audit_events')
        op.drop_index(op.f('ix_user_notification_preferences_user_id'), table_name='user_notification_preferences')
        op.drop_table('user_notification_preferences')
        op.drop_index(op.f('ix_user_ai_preferences_user_id'), table_name='user_ai_preferences')
        op.drop_table('user_ai_preferences')
        op.drop_index(op.f('ix_ukg_sessions_tenant_id'), table_name='ukg_sessions')
        op.drop_index(op.f('ix_ukg_sessions_session_id'), table_name='ukg_sessions')
        op.drop_table('ukg_sessions')
        op.drop_index('ix_ukg_knowledge_nodes_type_axis', table_name='ukg_knowledge_nodes')
        op.drop_index('ix_ukg_knowledge_nodes_tenant_id', table_name='ukg_knowledge_nodes')
        op.drop_index('ix_ukg_knowledge_nodes_node_type', table_name='ukg_knowledge_nodes')
        op.drop_index('ix_ukg_knowledge_nodes_axis_number', table_name='ukg_knowledge_nodes')
        op.drop_table('ukg_knowledge_nodes')
        op.drop_index(op.f('ix_ukg_ka_executions_tenant_id'), table_name='ukg_ka_executions')
        op.drop_table('ukg_ka_executions')
        op.drop_index(op.f('ix_ukg_edges_tenant_id'), table_name='ukg_edges')
        op.drop_index('ix_ukg_edges_edge_type', table_name='ukg_edges')
        op.drop_table('ukg_edges')
        op.drop_index(op.f('ix_truth_sessions_tenant_id'), table_name='truth_sessions')
        op.drop_index(op.f('ix_truth_sessions_session_id'), table_name='truth_sessions')
        op.drop_table('truth_sessions')
        op.drop_index(op.f('ix_truth_budgets_tenant_id'), table_name='truth_budgets')
        op.drop_table('truth_budgets')
        op.drop_index('ix_trace_runs_user_id', table_name='trace_runs')
        op.drop_index('ix_trace_runs_status', table_name='trace_runs')
        op.drop_index('ix_trace_runs_session_id', table_name='trace_runs')
        op.drop_index('ix_trace_runs_created_at', table_name='trace_runs')
        op.drop_table('trace_runs')
        op.drop_index('ix_simulation_sessions_user_status', table_name='simulation_sessions')
        op.drop_index('ix_simulation_sessions_user_id', table_name='simulation_sessions')
        op.drop_index('ix_simulation_sessions_status', table_name='simulation_sessions')
        op.drop_index('ix_simulation_sessions_created_at', table_name='simulation_sessions')
        op.drop_table('simulation_sessions')
        op.drop_index('ix_prompt_templates_key_version', table_name='prompt_templates')
        op.drop_index('ix_prompt_templates_key', table_name='prompt_templates')
        op.drop_index('ix_prompt_templates_approval', table_name='prompt_templates')
        op.drop_index('ix_prompt_templates_active', table_name='prompt_templates')
        op.drop_table('prompt_templates')
        op.drop_index(op.f('ix_password_history_user_id'), table_name='password_history')
        op.drop_table('password_history')
        op.drop_index('ix_model_routing_policy_name_version', table_name='model_routing_policies')
        op.drop_index('ix_model_routing_policy_name', table_name='model_routing_policies')
        op.drop_index('ix_model_routing_policy_active', table_name='model_routing_policies')
        op.drop_table('model_routing_policies')
        op.drop_index(op.f('ix_mcp_tools_tenant_id'), table_name='mcp_tools')
        op.drop_index(op.f('ix_mcp_tools_name'), table_name='mcp_tools')
        op.drop_table('mcp_tools')
        op.drop_index(op.f('ix_mcp_resources_uri'), table_name='mcp_resources')
        op.drop_index(op.f('ix_mcp_resources_tenant_id'), table_name='mcp_resources')
        op.drop_table('mcp_resources')
        op.drop_index(op.f('ix_mcp_prompts_tenant_id'), table_name='mcp_prompts')
        op.drop_index(op.f('ix_mcp_prompts_name'), table_name='mcp_prompts')
        op.drop_table('mcp_prompts')
        op.drop_table('llm_providers')
        op.drop_index('ix_feature_flags_key', table_name='feature_flags')
        op.drop_table('feature_flags')
        op.drop_index('ix_feature_flag_audit_key', table_name='feature_flag_audit_events')
        op.drop_index('ix_feature_flag_audit_actor', table_name='feature_flag_audit_events')
        op.drop_table('feature_flag_audit_events')
        op.drop_table('external_api_keys')
        op.drop_table('chat_sessions')
        op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
        op.drop_table('audit_logs')
        op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
        op.drop_index(op.f('ix_api_keys_key'), table_name='api_keys')
        op.drop_table('api_keys')
        op.drop_index('ix_users_username', table_name='users')
        op.drop_index('ix_users_email', table_name='users')
        op.drop_index('ix_users_created_at', table_name='users')
        op.drop_index('ix_users_active', table_name='users')
        op.drop_table('users')
        op.drop_index(op.f('ix_ukg_time_contexts_tenant_id'), table_name='ukg_time_contexts')
        op.drop_table('ukg_time_contexts')
        op.drop_index(op.f('ix_ukg_sectors_tenant_id'), table_name='ukg_sectors')
        op.drop_table('ukg_sectors')
        op.drop_index(op.f('ix_ukg_pillar_levels_tenant_id'), table_name='ukg_pillar_levels')
        op.drop_table('ukg_pillar_levels')
        op.drop_table('ukg_personas')
        op.drop_index(op.f('ix_ukg_nodes_tenant_id'), table_name='ukg_nodes')
        op.drop_index('ix_ukg_nodes_node_type', table_name='ukg_nodes')
        op.drop_index('ix_ukg_nodes_axis_number', table_name='ukg_nodes')
        op.drop_table('ukg_nodes')
        op.drop_index(op.f('ix_ukg_method_nodes_tenant_id'), table_name='ukg_method_nodes')
        op.drop_table('ukg_method_nodes')
        op.drop_index(op.f('ix_ukg_locations_tenant_id'), table_name='ukg_locations')
        op.drop_table('ukg_locations')
        op.drop_index(op.f('ix_ukg_knowledge_algorithms_tenant_id'), table_name='ukg_knowledge_algorithms')
        op.drop_table('ukg_knowledge_algorithms')
        op.drop_index(op.f('ix_ukg_domains_tenant_id'), table_name='ukg_domains')
        op.drop_table('ukg_domains')
        op.drop_index(op.f('ix_truth_link_messages_message_type'), table_name='truth_link_messages')
        op.drop_index(op.f('ix_truth_link_messages_message_id'), table_name='truth_link_messages')
        op.drop_table('truth_link_messages')
        op.drop_index(op.f('ix_mcp_servers_tenant_id'), table_name='mcp_servers')
        op.drop_index(op.f('ix_mcp_servers_server_id'), table_name='mcp_servers')
        op.drop_table('mcp_servers')
        op.drop_index('ix_cross_store_outbox_pending', table_name='cross_store_outbox_events')
        op.drop_index('ix_cross_store_outbox_entity', table_name='cross_store_outbox_events')
        op.drop_index('ix_cross_store_outbox_destination', table_name='cross_store_outbox_events')
        op.drop_table('cross_store_outbox_events')
        op.drop_index('ix_cross_store_materialization_state', table_name='cross_store_materialization_states')
        op.drop_table('cross_store_materialization_states')
        # ### end Alembic commands ###
