"""
Universal Knowledge Graph (UKG) System - Quad Persona Models

This module defines database models for the Quad Persona System,
enabling persistent storage of persona-based knowledge processing.
"""

import os
import logging
import uuid
from datetime import datetime
from typing import Dict, List, Any, Optional
from sqlalchemy import Column, Integer, String, Float, Boolean, DateTime, Text, ForeignKey, JSON
from sqlalchemy.orm import relationship
from app import db

logger = logging.getLogger(__name__)

class Persona(db.Model):
    """Model for Personas in the Quad Persona System."""
    __tablename__ = 'ukg_personas'
    
    id = Column(Integer, primary_key=True)
    uid = Column(String(255), unique=True, nullable=False)
    persona_id = Column(String(50), unique=True, nullable=False)  # e.g., "analyst", "explorer"
    name = Column(String(255), nullable=False)
    description = Column(Text, nullable=True)
    traits = Column(JSON, nullable=True)
    strengths = Column(JSON, nullable=True)
    focus = Column(Text, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    perspectives = relationship("Perspective", back_populates="persona")
    
    def to_dict(self):
        """Convert persona to dictionary."""
        return {
            'id': self.id,
            'uid': self.uid,
            'persona_id': self.persona_id,
            'name': self.name,
            'description': self.description,
            'traits': self.traits,
            'strengths': self.strengths,
            'focus': self.focus,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }


class Perspective(db.Model):
    """Model for Perspectives generated by personas on knowledge nodes."""
    __tablename__ = 'ukg_perspectives'
    
    id = Column(Integer, primary_key=True)
    uid = Column(String(255), unique=True, nullable=False)
    persona_id = Column(Integer, ForeignKey('ukg_personas.id'), nullable=False)
    knowledge_node_id = Column(Integer, ForeignKey('ukg_knowledge_nodes.id'), nullable=False)
    key_insights = Column(JSON, nullable=True)
    strengths_identified = Column(JSON, nullable=True)
    blind_spots = Column(JSON, nullable=True)
    recommendations = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    persona = relationship("Persona", back_populates="perspectives")
    knowledge_node = relationship("KnowledgeNode", back_populates="perspectives")
    
    def to_dict(self):
        """Convert perspective to dictionary."""
        return {
            'id': self.id,
            'uid': self.uid,
            'persona_id': self.persona_id,
            'knowledge_node_id': self.knowledge_node_id,
            'key_insights': self.key_insights,
            'strengths_identified': self.strengths_identified,
            'blind_spots': self.blind_spots,
            'recommendations': self.recommendations,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }


class IntegratedView(db.Model):
    """Model for Integrated Views synthesized from multiple perspectives."""
    __tablename__ = 'ukg_integrated_views'
    
    id = Column(Integer, primary_key=True)
    uid = Column(String(255), unique=True, nullable=False)
    knowledge_node_id = Column(Integer, ForeignKey('ukg_knowledge_nodes.id'), nullable=False)
    synthesis_method = Column(String(100), nullable=False)
    key_insights = Column(JSON, nullable=True)
    comprehensive_strengths = Column(JSON, nullable=True)
    potential_limitations = Column(JSON, nullable=True)
    balanced_recommendations = Column(JSON, nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    updated_at = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow)
    
    # Relationships
    knowledge_node = relationship("KnowledgeNode", back_populates="integrated_views")
    perspectives = Column(JSON, nullable=True)  # Store IDs of contributing perspectives
    
    def to_dict(self):
        """Convert integrated view to dictionary."""
        return {
            'id': self.id,
            'uid': self.uid,
            'knowledge_node_id': self.knowledge_node_id,
            'synthesis_method': self.synthesis_method,
            'key_insights': self.key_insights,
            'comprehensive_strengths': self.comprehensive_strengths,
            'potential_limitations': self.potential_limitations,
            'balanced_recommendations': self.balanced_recommendations,
            'perspectives': self.perspectives,
            'created_at': self.created_at.isoformat() if self.created_at else None,
            'updated_at': self.updated_at.isoformat() if self.updated_at else None
        }