"""Generate frontend and documentation views of the provider manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.llm_gateway.provider_manifest import (  # noqa: E402
    PROVIDERS,
    RAW_PROVIDER_MANIFEST,
)


FRONTEND_OUTPUT = ROOT / "frontend" / "lib" / "provider-manifest.generated.ts"
DOC_OUTPUT = ROOT / "docs" / "evaluation" / "AI_SYSTEM_CARD.md"


def _typescript() -> str:
    compact = json.dumps(RAW_PROVIDER_MANIFEST, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/generate_provider_manifest.py. Do not edit by hand.\n"
        f"export const PROVIDER_MANIFEST = {compact} as const;\n\n"
        "export const CONFIGURABLE_PROVIDER_TYPES: string[] = "
        "PROVIDER_MANIFEST.providers.map((provider) => provider.id);\n\n"
        "export const MODEL_LIBRARY: Record<string, string[]> = Object.fromEntries(\n"
        "  PROVIDER_MANIFEST.providers.map((provider) => [\n"
        "    provider.id,\n"
        "    provider.models.map((model) => model.id),\n"
        "  ])\n"
        ");\n\n"
        "export const DEFAULT_MODEL_BY_PROVIDER: Record<string, string> = Object.fromEntries(\n"
        "  PROVIDER_MANIFEST.providers.map((provider) => [provider.id, provider.default_model])\n"
        ");\n"
    )


def _canonical_document_current(path: Path) -> bool:
    """Verify the consolidated AI system card retains current manifest facts."""

    if not path.is_file():
        return False
    text = path.read_text(encoding="utf-8")
    folded = " ".join(text.split()).casefold()
    required = {
        "## Providers, models, cost, and quota controls",
        "The provider manifest is the only production model allowlist.",
        "unknown providers and undeclared models fail closed",
        "does not silently switch providers",
        "Missing, stale, malformed, or unmatched pricing is",
        "reported as `unknown`, never zero",
    }
    for provider in PROVIDERS:
        required.update({provider.label, provider.default_model, provider.request_api})
    return all(" ".join(item.split()).casefold() in folded for item in required)


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    normalized = content.rstrip() + "\n"
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == normalized
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(normalized, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = [
        _write_or_check(FRONTEND_OUTPUT, _typescript(), args.check),
        _canonical_document_current(DOC_OUTPUT),
    ]
    if args.check and not all(results):
        print("Provider manifest generated artifacts are stale.")
        return 1
    print("Provider manifest artifacts are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
