"""Generate frontend and documentation views of the provider manifest."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

from backend.llm_gateway.provider_manifest import (  # noqa: E402
    PROVIDERS,
    RAW_PROVIDER_MANIFEST,
)


FRONTEND_OUTPUT = ROOT / "frontend" / "lib" / "provider-manifest.generated.ts"
DOC_OUTPUT = ROOT / "docs" / "PROVIDER_MODEL_SUPPORT.md"


def _typescript() -> str:
    compact = json.dumps(RAW_PROVIDER_MANIFEST, indent=2, ensure_ascii=False)
    return (
        "// Generated by scripts/generate_provider_manifest.py. Do not edit by hand.\n"
        f"export const PROVIDER_MANIFEST = {compact} as const;\n\n"
        "export const CONFIGURABLE_PROVIDER_TYPES: string[] = "
        "PROVIDER_MANIFEST.providers.map((provider) => provider.id);\n\n"
        "export const MODEL_LIBRARY: Record<string, string[]> = Object.fromEntries(\n"
        "  PROVIDER_MANIFEST.providers.map((provider) => [\n"
        "    provider.id,\n"
        "    provider.models.map((model) => model.id),\n"
        "  ])\n"
        ");\n\n"
        "export const DEFAULT_MODEL_BY_PROVIDER: Record<string, string> = Object.fromEntries(\n"
        "  PROVIDER_MANIFEST.providers.map((provider) => [provider.id, provider.default_model])\n"
        ");\n"
    )


def _markdown() -> str:
    lines = [
        "# Provider and Model Support",
        "",
        "This file is generated by `scripts/generate_provider_manifest.py` from",
        "`config/provider_manifest.v1.json`. The manifest is the product contract;",
        "backend, frontend, tests, and this document must not maintain separate lists.",
        "",
        "| Provider | Supported model | API | Native stream capability | Pricing metadata |",
        "|---|---|---|---|---|",
    ]
    for provider in PROVIDERS:
        lines.append(
            f"| {provider.label} (`{provider.id}`) | `{provider.default_model}` | "
            f"`{provider.request_api}` | {'yes' if provider.native_streaming else 'no'} | "
            f"{provider.pricing_status} |"
        )
    lines.extend(
        [
            "",
            "## Runtime rules",
            "",
            "- Only the two declared provider IDs are accepted in production configuration.",
            "- `gemini` is accepted only as a compatibility alias and normalizes to `google`.",
            "- Unknown providers and undeclared models fail closed; they never fall back to OpenAI.",
            "- One user-selected provider/model is used. Cross-provider failover is not implicit.",
            "- Native streaming capability does not mean every UI path is native streaming. A path",
            "  that chunks a completed response must identify itself as `buffered` output.",
            "- Pricing remains unknown until an owner-approved, dated pricing record is installed.",
            "  Unknown price is governed by call/token ceilings and is never represented as zero.",
            "",
        ]
    )
    return "\n".join(lines)


def _write_or_check(path: Path, content: str, check: bool) -> bool:
    normalized = content.rstrip() + "\n"
    if check:
        return path.exists() and path.read_text(encoding="utf-8") == normalized
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(normalized, encoding="utf-8")
    return True


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    results = [
        _write_or_check(FRONTEND_OUTPUT, _typescript(), args.check),
        _write_or_check(DOC_OUTPUT, _markdown(), args.check),
    ]
    if args.check and not all(results):
        print("Provider manifest generated artifacts are stale.")
        return 1
    print("Provider manifest artifacts are current.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
