#!/usr/bin/env python3
"""Generate the active documentation portal from the Phase 16 authority."""

from __future__ import annotations

import argparse
import json
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

try:
    from generate_documentation_authority import DEFAULT_CONFIG, ROOT, load_authority
except ModuleNotFoundError:
    from scripts.generate_documentation_authority import (
        DEFAULT_CONFIG,
        ROOT,
        load_authority,
    )


DEFAULT_OUTPUT = ROOT / "docs" / "README.md"
DEFAULT_TODO = ROOT / "TODO.md"
DEFAULT_CLOSURE = (
    ROOT / "reports" / "production-readiness" / "2026" / "phase-16"
    / "document-replacement-closure.json"
)
CLASS_ORDER = (
    "product_public",
    "user_admin_support",
    "engineering_maintenance",
    "assurance_release_external",
)
CLASS_TITLES = {
    "product_public": "Product and public",
    "user_admin_support": "User, administrator, and support",
    "engineering_maintenance": "Engineering and maintenance",
    "assurance_release_external": "Assurance, release, and external review",
}


def _load_closure(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {"status": "not_evaluated", "summary": {}}
    return json.loads(path.read_text(encoding="utf-8"))


def _todo_field(path: Path, field: str) -> str:
    if not path.is_file():
        return "not_evaluated"
    prefix = f"| {field} |"
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(prefix):
            return line.split("|", 3)[2].strip()
    return "not_evaluated"


def render(
    authority: dict[str, Any],
    closure: dict[str, Any],
    *,
    current_phase: str = "not_evaluated",
) -> str:
    summary = closure.get("summary", {})
    canonical = authority["canonical_documents"]
    lines = [
        "# DataLogicEngine documentation portal",
        "",
        "> Generated by `scripts/generate_documentation_portal.py` from",
        "> `config/documentation-authority.json` and the current CP16-F closure report.",
        "> Do not hand-edit.",
        "",
        "## Authority and release status",
        "",
        f"- Generated: `{datetime.now(UTC).date().isoformat()}`",
        f"- Documentation authority: `{authority['program_version']}` (`{authority['status']}`)",
        f"- Canonical hand-maintained documents: `{len(canonical)}` of `{authority['max_hand_maintained_canonical_documents']}`",
        f"- CP16-F replacement status: `{closure.get('status', 'not_evaluated')}`",
        f"- Routed sources: `{summary.get('source_count', 0)}`; archived: `{summary.get('archived_source_count', 0)}`; unmigrated links: `{summary.get('unmigrated_link_count', 0)}`",
        f"- Current program checkpoint: {current_phase}",
        "- Current KA evidence: Phase 19 CP19-A through CP19-H passed with 213 canonical capabilities, one implementation and primary subsystem owner per KA, 132 live registry entries, 89 production-enabled capabilities, zero unregistered Layer 9 implementations, one runtime manifest, typed caller parity, 213 positive and 213 negative selector fixtures, a current 136-edge zero-cycle dependency graph, one typed causal L1-L10 product lifecycle, full fail-closed execution of every L9/L10 KA, causal axes 8-11 `KA-012` -> `KA-013` -> `KA-030` persona influence, one trace-accounted manifest-owned 12-step workflow, and one manifest-owned Truth/data/knowledge lifecycle. Entry and L8 share typed policy; authorized memory recall and release-gated promotion are scope/retention/rollback safe; TruthLink/FROST publication is causal and release-blocking; secure ingestion KAs run before materialization; and authoritative services retain real effect/receipt ownership. Thirteen focused, 79 affected-subsystem, 767 KA, six TypeScript SDK, and 2,541 full-source tests pass; the full suite has 19 skipped and 21 known warnings. CP19-I extended subsystem/effect integration is active; the rebuild remains blocked through CP19-L.",
        "- Production/public release: **NO-GO** until the installed, accessibility, security, signing, external-review, and release gates in root `TODO.md` pass.",
        "",
        "The authoritative program is root `PRODUCTION_COMPLETION_PLAN_2026.md`; root",
        "`TODO.md` is its execution ledger and root `HANDOFF.md` is the current checkpoint.",
        "Historical documents under `docs/archive/` retain evidence and context but are",
        "not current product or operating authority.",
        "",
        "## Start here by role",
        "",
        "| Role | Read first |",
        "|---|---|",
        "| User or evaluator | `README.md`, `docs/PRODUCT_REQUIREMENTS.md`, `docs/INSTALLATION_GUIDE.md`, `docs/USER_GUIDE.md` |",
        "| Owner or operator | `docs/ADMINISTRATOR_OPERATIONS_GUIDE.md`, `docs/TROUBLESHOOTING_SUPPORT_GUIDE.md`, `docs/MAINTENANCE_DISASTER_RECOVERY.md` |",
        "| Engineer or architect | `docs/DEVELOPER_GUIDE.md`, `docs/ARCHITECTURE.md`, `docs/DATA_ARCHITECTURE.md`, `docs/INTERFACE_INTEGRATION.md` |",
        "| Security, privacy, or AI reviewer | `SECURITY.md`, `docs/SECURITY_ARCHITECTURE.md`, `docs/PRIVACY_IMPACT_ASSESSMENT.md`, `docs/evaluation/AI_SYSTEM_CARD.md` |",
        "| Accessibility reviewer | `docs/ACCESSIBILITY_CONFORMANCE_REPORT.md`, `docs/USER_GUIDE.md` |",
        "| Release or external reviewer | `docs/REQUIREMENTS_TRACEABILITY.md`, `docs/VERIFICATION_VALIDATION_REPORT.md`, `docs/RELEASE_READINESS_RECORD.md`, `docs/PROFESSIONAL_REVIEW_INDEX.md` |",
        "",
        "## Canonical document set",
        "",
    ]
    for document_class in CLASS_ORDER:
        lines.extend(
            [
                f"### {CLASS_TITLES[document_class]}",
                "",
                "| ID | Document | Authority |",
                "|---|---|---|",
            ]
        )
        for item in canonical:
            if item["class"] != document_class:
                continue
            lines.append(f"| `{item['id']}` | `{item['path']}` | {item['title']} |")
        lines.append("")
    lines.extend(
        [
            "## Generated companions and machine-readable contracts",
            "",
            "- `docs/DOCUMENTATION_BOM.md` - controlled canonical bill of materials.",
            "- `docs/DOCUMENTATION_CROSSWALK.md` - complete file disposition inventory.",
            "- `docs/GENERATED_STRUCTURE.md` and `docs/FILE_INVENTORY.csv` - repository inventory.",
            "- `docs/openapi.yaml` - API schema where applicable.",
            "- `docs/generated/PRODUCTION_CONTRACT_INDEX.md` - generated product, provider, service, route, environment, and installer parity view.",
            "- `docs/adr/README.md` - historical ADR index; current decisions are consolidated into canonical architecture documents.",
            "- `reports/production-readiness/2026/` - phase and release evidence.",
            "",
            "## Historical and retained evidence",
            "",
            "The CP16-F baseline records SHA-256 and Git blob identity for every routed",
            "source before archival. The closure report records its canonical target, archive",
            "location, retained hash, technical review, and link-migration result. Archived",
            "material must be checked against current code and canonical documents before reuse.",
            "",
            "## Validation",
            "",
            "```powershell",
            "python scripts/generate_documentation_authority.py",
            "python scripts/verify_documentation_bom.py",
            "python scripts/verify_doc_authority.py",
            "python scripts/verify_document_replacement_closure.py",
            "python scripts/verify_docs_references.py",
            "python scripts/verify_requirements_traceability.py",
            "```",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--config", type=Path, default=DEFAULT_CONFIG)
    parser.add_argument("--closure", type=Path, default=DEFAULT_CLOSURE)
    parser.add_argument("--todo", type=Path, default=DEFAULT_TODO)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args(argv)
    args.output.write_text(
        render(
            load_authority(args.config),
            _load_closure(args.closure),
            current_phase=_todo_field(args.todo, "Current phase"),
        ),
        encoding="utf-8",
    )
    print(f"Documentation portal generated: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
