#!/usr/bin/env python3
"""Generate the Phase 17 product/build contract parity index."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_ROUTE_REPORT = (
    ROOT / "reports" / "production-readiness" / "2026" / "phase-17"
    / "route-manifest.json"
)
DEFAULT_OUTPUT = ROOT / "docs" / "generated" / "PRODUCTION_CONTRACT_INDEX.md"
ENV_KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_]*)=")


def _json(path: Path) -> dict[str, Any]:
    return json.loads(path.read_text(encoding="utf-8"))


def _environment_keys(path: Path) -> list[str]:
    keys: list[str] = []
    for line in path.read_text(encoding="utf-8").splitlines():
        match = ENV_KEY.match(line.strip())
        if match:
            keys.append(match.group(1))
    return sorted(set(keys))


def _artifact_name(builder_path: Path) -> str:
    match = re.search(
        r'''(?m)^\s*artifactName:\s*["']?([^"'\r\n]+)''',
        builder_path.read_text(encoding="utf-8"),
    )
    if not match:
        raise ValueError("electron-builder artifactName is missing")
    return match.group(1).strip()


def render(*, root: Path = ROOT, route_report: Path = DEFAULT_ROUTE_REPORT) -> str:
    versions = _json(root / "config" / "product-versions.json")
    providers = _json(root / "config" / "provider_manifest.v1.json")
    services = _json(root / "deploy" / "internal-data-plane.candidate-lock.json")
    routes = _json(route_report)
    openapi = yaml.safe_load((root / "docs" / "openapi.yaml").read_text(encoding="utf-8"))
    environment = _environment_keys(root / ".env.template")
    product = versions["product"]
    route_summary = routes["summary"]
    lines = [
        "# Generated production contract index",
        "",
        "> Generated by `scripts/generate_documentation_contract_index.py` from",
        "> repository authorities and live route inventory. Do not hand-edit.",
        "",
        "## Product and installer",
        "",
        "| Field | Authority value |",
        "|---|---|",
        f"| Product | `{product['name']}` |",
        f"| Product version | `{product['version']}` |",
        f"| Windows file version | `{product['windows_file_version']}` |",
        f"| Release channel | `{product['release_channel']}` |",
        f"| Installer artifact pattern | `{_artifact_name(root / 'frontend' / 'electron-builder.yml')}` |",
        "",
        "## Provider and model allowlist",
        "",
        "| Provider ID | Label | Models | Request API | Key environment | Pricing |",
        "|---|---|---|---|---|---|",
    ]
    for provider in providers["providers"]:
        models = ", ".join(f"`{item['id']}`" for item in provider["models"])
        keys = ", ".join(f"`{item}`" for item in provider["api_key_environment"])
        lines.append(
            f"| `{provider['id']}` | {provider['label']} | {models} | "
            f"`{provider['request_api']}` | {keys} | `{provider['pricing']['status']}` |"
        )
    lines.extend(
        [
            "",
            "## Internal service candidate lock",
            "",
            f"Status: `{services['status']}`. Runtime: `{services['runtime']['name']} {services['runtime']['version']}`. "
            f"Production provisioning authorized: `{str(services['production_provisioning_authorized']).lower()}`.",
            "",
            "| Service key | Product | Version | Production approved | Candidate identity |",
            "|---|---|---|---|---|",
        ]
    )
    for key, service in services["services"].items():
        product_name = service.get("product", key)
        identity = service.get("image", service.get("linux_amd64_digest", "not recorded"))
        lines.append(
            f"| `{key}` | `{product_name}` | `{service['version']}` | "
            f"`{str(service.get('production_approved', False)).lower()}` | `{identity}` |"
        )
    lines.extend(
        [
            "",
            "## API and live route inventory",
            "",
            "| Field | Value |",
            "|---|---|",
            f"| OpenAPI format | `{openapi['openapi']}` |",
            f"| OpenAPI title | `{openapi['info']['title']}` |",
            f"| OpenAPI document version | `{openapi['info']['version']}` |",
            f"| OpenAPI path count | `{len(openapi.get('paths', {}))}` |",
            f"| Live Flask route count | `{route_summary['routes']}` |",
            f"| Unclassified live routes | `{route_summary['unclassified']}` |",
            f"| GraphQL operations | `{route_summary['graphql_operations']}` |",
            f"| Electron IPC channels | `{route_summary['ipc_channels']}` |",
            "",
            "## Environment contract",
            "",
            f"The tracked `.env.template` declares `{len(environment)}` unique keys. "
            "Presence in this generated list is configuration discoverability, not permission",
            "to use an unsupported deployment or bypass production validation.",
            "",
            "| Environment key |",
            "|---|",
            *[f"| `{key}` |" for key in environment],
            "",
            "## Generation authorities",
            "",
            "- `config/product-versions.json`",
            "- `config/provider_manifest.v1.json`",
            "- `deploy/internal-data-plane.candidate-lock.json`",
            "- `reports/production-readiness/2026/phase-17/route-manifest.json`",
            "- `docs/openapi.yaml`",
            "- `.env.template`",
            "- `frontend/electron-builder.yml`",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--route-report", type=Path, default=DEFAULT_ROUTE_REPORT)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args(argv)
    expected = render(route_report=args.route_report)
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != expected:
            print(f"Generated documentation contract index is stale: {args.output}")
            return 1
        print("Generated documentation contract index matches authorities")
        return 0
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(expected, encoding="utf-8")
    print(f"Generated documentation contract index: {args.output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
