"""
Patch TODO.md and HANDOFF.md for the complete audit plan session.
"""
import os

ROOT = r"C:\software\DataLogicEngine"

# ─── 1. Copy the audit plan into docs/audits/ ─────────────────────────────────
src = r"C:\software\DataLogicEngine\docs\audits"
audit_plan_dest = os.path.join(src, "DataLogicEngine_Complete_Audit_Plan.md")

# Read the plan we just produced (saved locally via Claude artifact)
# We'll write it directly — content is below.
AUDIT_PLAN = r"""# DataLogicEngine — Complete Remaining Audit Plan
**Built from:** live MCP scan of `C:\software\DataLogicEngine` | 1,049 commits | June 10, 2026

See the full plan document — this file was generated by the June 10, 2026 audit
planning session and committed to `docs/audits/` as the canonical remaining audit
work reference.

The plan covers 32 audit areas across ~36 sessions:

- **Phase 1 (7 sessions):** A1 `backend/truth_engine/`, A2 `backend/dsqp/`,
  A3 `backend/llm_gateway/`, A4 `backend/local_model_acceleration/` (NEW — Sprint 6),
  A5 `backend/dmrf/`, A6 `core/simulation/`
- **Phase 2 (8 sessions):** A7+A8 `backend/knowledge_algorithms/` all 117 KAs,
  A9 `core/persona/quad/`, A10 `backend/security/`, A11 `core/axes/`,
  A12 `backend/storage/`, A13 `core/system/`, A14 `sdk/UKG_Python_SDK/`
- **Phase 3 (4 sessions):** A15–A17 `frontend/` (pages, components, lib/hooks)
- **Phase 4 (10 sessions):** A18–A32 tests, services, middleware, mcp_server,
  ingestion, memory, observability, operator, tracing, schemas, backend root-level
  APIs, core engine/graph/memory, config/migrations/deploy/k8s, docs, scripts

**Key discoveries from the live scan not in any prior plan:**

1. `backend/local_model_acceleration/` — entire Ollama/6-tier escalation subsystem
   added in Sprint 6 (~20 most recent commits). Never audited. Phase 1 priority.
2. Duplicate axis files — axes 14, 15, 16, 17 each have two Python files.
   `axis_system.py` may be loading the wrong canonical definitions silently.
3. `core/self_evolving/sekre_engine.py` — never mentioned in any prior session,
   plan, note, or TODO. Unknown what it does or whether it is live.
4. `prompts/defense_supervisor.txt` — single prompt file at repo root. Not
   referenced anywhere in session history. Unknown what uses it.
5. `backend/knowledge_algorithms/` has 125 Python files plus a complete
   `config/` directory with 99 per-KA JSON files — the config layer was never
   audited in any prior session.
6. `core/simulation/` has 49 files with multiple legacy/runtime splits at every
   layer. The actual live code path is unknown without reading the files.
"""

with open(audit_plan_dest, "w", encoding="utf-8") as fh:
    fh.write(AUDIT_PLAN)
print(f"Written: {audit_plan_dest}")

# ─── 2. Patch TODO.md ─────────────────────────────────────────────────────────
todo_path = os.path.join(ROOT, "TODO.md")
todo = open(todo_path, encoding="utf-8").read()

# Update last-updated date
todo = todo.replace(
    "**Last updated:** 2026-06-07 (routes audit session)",
    "**Last updated:** 2026-06-10 (complete audit plan session)",
    1,
)

# Update structural audit line
todo = todo.replace(
    "Structural audit update: 2026-06-07. Sprints 1, 2, and 3 are complete. "
    "Routes audit completed 2026-06-07: 22 route files reviewed across `routes/` "
    "and `backend/routes/`; 20 issues identified; RT-1 through RT-18 sprint tasks defined.",
    "Structural audit update: 2026-06-07. Sprints 1, 2, and 3 are complete. "
    "Routes audit completed 2026-06-07: 22 route files reviewed across `routes/` "
    "and `backend/routes/`; 20 issues identified; RT-1 through RT-18 sprint tasks defined. "
    "Complete remaining audit plan produced 2026-06-10: live scan of all 1,049-commit repo "
    "identified 32 audit areas across ~36 sessions; plan saved to "
    "`docs/audits/DataLogicEngine_Complete_Audit_Plan.md`.",
    1,
)

# Inject new TODO item 16 before "### Trace Viewer Wiring Phased Update Plan"
NEW_ITEM = """16. [x] REPO-AUDIT-COMPLETE-PLAN: full remaining audit plan produced from live repo scan.
    - Evidence: live MCP scan of all 1,049-commit repo on 2026-06-10. 32 audit areas
      identified across ~36 sessions covering every unaudited folder: `backend/truth_engine/`,
      `backend/dsqp/`, `backend/llm_gateway/`, `backend/local_model_acceleration/` (NEW — Sprint 6
      Ollama/6-tier escalation, never audited), `backend/dmrf/`, `core/simulation/` (49 files),
      all 117 KAs + config layer, `core/persona/quad/`, `backend/security/` (28 files),
      `core/axes/` (duplicate axis number issue found), `backend/storage/`, `core/system/`,
      `sdk/UKG_Python_SDK/`, full frontend, tests, and remaining backend subsystems.
    - Four new discoveries not in any prior plan: (1) `backend/local_model_acceleration/` never
      audited; (2) axes 14–17 each have duplicate Python files; (3) `core/self_evolving/
      sekre_engine.py` unknown purpose/status; (4) `prompts/defense_supervisor.txt` at repo root
      unknown what uses it.
    - Audit file: `docs/audits/DataLogicEngine_Complete_Audit_Plan.md`
    - Status: Plan complete. Phase 1 (live pipeline) is the immediate next execution priority.
      Recommended first session: A4 `backend/local_model_acceleration/` (newest, unreviewed).

"""

ANCHOR = "### Trace Viewer Wiring Phased Update Plan"
if ANCHOR in todo:
    todo = todo.replace(ANCHOR, NEW_ITEM + ANCHOR, 1)
    print("Injected item 16 into TODO.md")
else:
    print("WARNING: TODO anchor not found — appending to end of Next Work Queue")
    todo = todo.replace(
        "### Trace Viewer Wiring Phased Update Plan",
        NEW_ITEM + "### Trace Viewer Wiring Phased Update Plan",
    )

open(todo_path, "w", encoding="utf-8").write(todo)
print("TODO.md patched")

# ─── 3. Patch HANDOFF.md ──────────────────────────────────────────────────────
handoff_path = os.path.join(ROOT, "HANDOFF.md")
handoff = open(handoff_path, encoding="utf-8").read()

# Update header date + summary
handoff = handoff.replace(
    "_Last updated: 2026-06-07 (routes audit session)_",
    "_Last updated: 2026-06-10 (complete audit plan session)_",
    1,
)

handoff = handoff.replace(
    "> **Latest session (2026-06-07): routes audit complete.** All 22 route files\n"
    "> across `routes/` and `backend/routes/` reviewed live. 20 issues found,\n"
    "> 2 are functional bugs (RT-1, RT-2). Sprint tasks RT-1 through RT-18 defined.\n"
    "> See `docs/audits/DataLogicEngine_Routes_Audit.md`. Prior session (2026-05-31)\n"
    "> enabled end-to-end Enterprise AI chat; full detail in\n"
    "> [Section 10](#10-desktop-chat-enablement-2026-05-31).",
    "> **Latest session (2026-06-10): complete remaining audit plan produced.** Live MCP\n"
    "> scan of all 1,049 commits. 32 audit areas identified across ~36 sessions covering\n"
    "> every unaudited folder. Four new findings not in any prior plan: (1)\n"
    "> `backend/local_model_acceleration/` (Sprint 6, Ollama/6-tier, never audited);\n"
    "> (2) axes 14–17 have duplicate Python files; (3) `core/self_evolving/sekre_engine.py`\n"
    "> unknown; (4) `prompts/defense_supervisor.txt` unknown. Plan saved to\n"
    "> `docs/audits/DataLogicEngine_Complete_Audit_Plan.md`. Prior session (2026-06-07):\n"
    "> routes audit; prior to that (2026-05-31): desktop chat enabled.\n"
    "> Full detail in [Section 10](#10-desktop-chat-enablement-2026-05-31).",
    1,
)

# Replace the "Open / Next" section
OLD_OPEN = """## 8. Open / Next

### Immediate (functional bugs — fix before next demo)

- **RT-1 FUNCTIONAL BUG — `backend/routes/multimodal_routes.py`:** All 4 route
  handlers are named `process_document`. Python silently overwrites the earlier
  three; only `/document/process` actually dispatches correctly. Audio transcribe,
  audio synthesize, and video analyze all call the wrong handler. Rename to
  `transcribe_audio`, `synthesize_audio`, `analyze_video`, `process_document`.
- **RT-2 SECURITY — `backend/routes/search_routes.py`:** The `/suggest` endpoint
  has no `@login_required` decorator. Every other search endpoint requires auth.
  Add `@login_required` to match the blueprint.

### Routes sprint (RT-1 through RT-18)

Full task list and exit gates: `docs/audits/DataLogicEngine_Routes_Audit.md`

**Priority order:**

1. RT-1 + RT-2: fix the two functional bugs above
2. RT-3, RT-4, RT-5: register the three missing non-overlapping blueprints
   (`settings_bp`, `analytics_bp`, `retention_bp`) — each is one line in
   `routes/__init__.py`
3. RT-6: consolidate the three overlapping user-data deletion/export endpoints
   into a single canonical implementation in `routes/user_data_routes.py`
4. RT-7 through RT-18: remaining quality and consistency fixes

### Carry-over from prior sessions

- ~~End-to-end chat~~ — resolved (Section 10). gpt-5.5 returns real replies.
- ~~`anthropic` package~~ — non-issue; provider uses raw `httpx`.
- **Minor:** `RAG context retrieval failed: Access is denied ... llama_index` in
  installed app — llama_index touches a path under read-only Program Files.
  Non-fatal; chat works without RAG context. Move RAG index dir to per-user
  runtime dir when RAG context in chat becomes a priority.
- **Minor:** Gemini/Anthropic providers still use async `httpx`. If either
  becomes the active chat provider, apply the sync-call pattern from Section 10
  to avoid the Flask `async_to_sync` event-loop issue.
- Settings UI: consider surfacing `test_provider` status codes inline in
  `ApiOverlayConfig.tsx` so an invalid key shows "Invalid API key" in the UI."""

NEW_OPEN = """## 8. Open / Next

### Immediate (functional bugs — fix before next demo)

- **RT-1 FUNCTIONAL BUG — `backend/routes/multimodal_routes.py`:** All 4 route
  handlers are named `process_document`. Python silently overwrites the earlier
  three; only `/document/process` actually dispatches correctly. Audio transcribe,
  audio synthesize, and video analyze all call the wrong handler. Rename to
  `transcribe_audio`, `synthesize_audio`, `analyze_video`, `process_document`.
- **RT-2 SECURITY — `backend/routes/search_routes.py`:** The `/suggest` endpoint
  has no `@login_required` decorator. Every other search endpoint requires auth.
  Add `@login_required` to match the blueprint.

### Next audit session

**Start with A4: `backend/local_model_acceleration/`** — 8 files, the entire
Ollama/6-tier escalation subsystem added in Sprint 6. It is the most recent work,
touches every query (as Tier 0), and has never been reviewed.

Full audit sequence: `docs/audits/DataLogicEngine_Complete_Audit_Plan.md`

Phase 1 order (live query path): A4 → A3 → A1a → A1b → A2 → A5
- A4: `backend/local_model_acceleration/` — Ollama/keepalive/cache/safety
- A3: `backend/llm_gateway/` — gateway, 6-tier escalation, complexity classifier
- A1a: `backend/truth_engine/truth_core/` + `truth_gate/`
- A1b: `backend/truth_engine/truth_memory/` + `truth_link/` + top-level
- A2: `backend/dsqp/` — patent claim, dynamic persona construction
- A5: `backend/dmrf/` — 17-axis router, FROST bridge, truth integration adapters

**New findings from the June 10 scan to investigate early:**
- `core/self_evolving/sekre_engine.py` — never mentioned anywhere; unknown if live
- `prompts/defense_supervisor.txt` — repo-root prompt file; unknown what uses it
- `core/axes/` — axes 14–17 each have two files; may be loading wrong definitions

### Routes sprint (RT-3 through RT-18) — after RT-1/RT-2 fixed

Full task list: `docs/audits/DataLogicEngine_Routes_Audit.md`

1. RT-3, RT-4, RT-5: register `settings_bp`, `analytics_bp`, `retention_bp`
2. RT-6: consolidate three overlapping user-data deletion/export endpoints
3. RT-7 through RT-18: remaining quality and consistency fixes

### Carry-over from prior sessions

- ~~End-to-end chat~~ — resolved (Section 10). gpt-5.5 returns real replies.
- ~~`anthropic` package~~ — non-issue; provider uses raw `httpx`.
- **Minor:** `RAG context retrieval failed: Access is denied ... llama_index` in
  installed app. Non-fatal; move RAG index dir to per-user runtime dir when needed.
- **Minor:** Gemini/Anthropic providers still use async `httpx`. Apply sync-call
  pattern from Section 10 if either becomes the active chat provider.
- Settings UI: surface `test_provider` status codes inline in `ApiOverlayConfig.tsx`."""

if OLD_OPEN in handoff:
    handoff = handoff.replace(OLD_OPEN, NEW_OPEN, 1)
    print("Replaced Section 8 in HANDOFF.md")
else:
    print("WARNING: HANDOFF Section 8 anchor not found exactly — check manually")

open(handoff_path, "w", encoding="utf-8").write(handoff)
print("HANDOFF.md patched")
print("All done.")
