#!/bin/bash
# Quick SSL Setup with Let's Encrypt for DataLogicEngine
# This script automates SSL certificate setup for production

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

echo "========================================"
echo "DataLogicEngine - SSL Setup (Let's Encrypt)"
echo "========================================"
echo ""

# Check if running as root or with sudo
if [ "$EUID" -ne 0 ]; then
    echo -e "${RED}✗ This script must be run as root or with sudo${NC}"
    echo "Usage: sudo ./scripts/setup_ssl_letsencrypt.sh"
    exit 1
fi

# Check if certbot is installed
if ! command -v certbot &> /dev/null; then
    echo -e "${YELLOW}⚠ Certbot not found. Installing...${NC}"

    # Detect OS
    if [ -f /etc/debian_version ]; then
        apt-get update
        apt-get install -y certbot python3-certbot-nginx
    elif [ -f /etc/redhat-release ]; then
        yum install -y certbot python3-certbot-nginx
    else
        echo -e "${RED}✗ Unsupported OS. Please install certbot manually.${NC}"
        exit 1
    fi

    echo -e "${GREEN}✓ Certbot installed${NC}"
fi

echo ""
echo -e "${BLUE}Please provide the following information:${NC}"
echo ""

# Get domain
read -p "Enter your domain (e.g., yourdomain.com): " DOMAIN

if [ -z "$DOMAIN" ]; then
    echo -e "${RED}✗ Domain is required${NC}"
    exit 1
fi

# Get additional domains
read -p "Enter additional domains (comma-separated, or press Enter to skip): " ADDITIONAL_DOMAINS

# Get email
read -p "Enter your email address (for certificate expiration notices): " EMAIL

if [ -z "$EMAIL" ]; then
    echo -e "${RED}✗ Email is required${NC}"
    exit 1
fi

echo ""
echo "========================================"
echo "Configuration Summary"
echo "========================================"
echo "Primary domain: $DOMAIN"
if [ ! -z "$ADDITIONAL_DOMAINS" ]; then
    echo "Additional domains: $ADDITIONAL_DOMAINS"
fi
echo "Email: $EMAIL"
echo ""

read -p "Proceed with certificate request? (y/N): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Yy]$ ]]; then
    echo "Aborted."
    exit 1
fi

echo ""
echo "========================================"
echo "Obtaining SSL Certificate"
echo "========================================"
echo ""

# Build certbot command
CERTBOT_CMD="certbot certonly --standalone"
CERTBOT_CMD="$CERTBOT_CMD -d $DOMAIN"

if [ ! -z "$ADDITIONAL_DOMAINS" ]; then
    # Split comma-separated domains and add -d flag for each
    IFS=',' read -ra DOMAINS <<< "$ADDITIONAL_DOMAINS"
    for d in "${DOMAINS[@]}"; do
        d=$(echo "$d" | xargs)  # Trim whitespace
        CERTBOT_CMD="$CERTBOT_CMD -d $d"
    done
fi

CERTBOT_CMD="$CERTBOT_CMD --email $EMAIL --agree-tos --non-interactive"

echo -e "${YELLOW}Note: Make sure ports 80 and 443 are open and your application is stopped.${NC}"
echo ""

read -p "Stop application before continuing? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo "Stopping application..."
    systemctl stop ukg-backend 2>/dev/null || true
    systemctl stop nginx 2>/dev/null || true
    echo -e "${GREEN}✓ Application stopped${NC}"
fi

echo ""
echo "Running: $CERTBOT_CMD"
echo ""

# Run certbot
if $CERTBOT_CMD; then
    echo -e "${GREEN}✓ Certificate obtained successfully!${NC}"
else
    echo -e "${RED}✗ Certificate request failed${NC}"
    exit 1
fi

echo ""
echo "========================================"
echo "Certificate Information"
echo "========================================"
echo ""

CERT_PATH="/etc/letsencrypt/live/$DOMAIN"
echo "Certificates saved to: $CERT_PATH"
echo ""
echo "Files:"
echo "  - Certificate: $CERT_PATH/fullchain.pem"
echo "  - Private Key: $CERT_PATH/privkey.pem"
echo "  - Chain: $CERT_PATH/chain.pem"
echo ""

# Check if nginx is installed
if command -v nginx &> /dev/null; then
    echo "========================================"
    echo "Nginx Configuration"
    echo "========================================"
    echo ""

    read -p "Create nginx configuration? (Y/n): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Nn]$ ]]; then
        # Create nginx config
        CONFIG_FILE="/etc/nginx/sites-available/datalogicengine"

        cat > "$CONFIG_FILE" <<EOF
# DataLogicEngine Nginx Configuration
# Auto-generated by setup_ssl_letsencrypt.sh

# HTTP -> HTTPS Redirect
server {
    listen 80;
    listen [::]:80;
    server_name $DOMAIN${ADDITIONAL_DOMAINS:+ }${ADDITIONAL_DOMAINS//,/ };

    location /.well-known/acme-challenge/ {
        root /var/www/html;
    }

    location / {
        return 301 https://\$server_name\$request_uri;
    }
}

# HTTPS Server
server {
    listen 443 ssl http2;
    listen [::]:443 ssl http2;
    server_name $DOMAIN${ADDITIONAL_DOMAINS:+ }${ADDITIONAL_DOMAINS//,/ };

    # SSL Configuration
    ssl_certificate $CERT_PATH/fullchain.pem;
    ssl_certificate_key $CERT_PATH/privkey.pem;

    # SSL Security Settings
    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers 'ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384';
    ssl_prefer_server_ciphers off;

    # HSTS
    add_header Strict-Transport-Security "max-age=63072000; includeSubDomains; preload" always;

    # SSL Session
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 10m;

    # OCSP Stapling
    ssl_stapling on;
    ssl_stapling_verify on;
    ssl_trusted_certificate $CERT_PATH/chain.pem;
    resolver 8.8.8.8 8.8.4.4 valid=300s;
    resolver_timeout 5s;

    # Security Headers
    add_header X-Frame-Options "DENY" always;
    add_header X-Content-Type-Options "nosniff" always;
    add_header X-XSS-Protection "1; mode=block" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;

    # Proxy to Flask Backend
    location / {
        proxy_pass http://127.0.0.1:5000;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;

        # WebSocket support
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";

        # Timeouts
        proxy_connect_timeout 60s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;
    }

    # Static files (if needed)
    location /static {
        alias /var/www/datalogicengine/static;
        expires 1y;
        add_header Cache-Control "public, immutable";
    }
}
EOF

        echo -e "${GREEN}✓ Nginx configuration created: $CONFIG_FILE${NC}"

        # Enable site
        if [ ! -e "/etc/nginx/sites-enabled/datalogicengine" ]; then
            ln -s "$CONFIG_FILE" /etc/nginx/sites-enabled/datalogicengine
            echo -e "${GREEN}✓ Site enabled${NC}"
        fi

        # Test nginx configuration
        echo ""
        echo "Testing nginx configuration..."
        if nginx -t; then
            echo -e "${GREEN}✓ Nginx configuration valid${NC}"
        else
            echo -e "${RED}✗ Nginx configuration has errors${NC}"
            exit 1
        fi
    fi
fi

echo ""
echo "========================================"
echo "Auto-Renewal Setup"
echo "========================================"
echo ""

# Test renewal
echo "Testing certificate renewal..."
if certbot renew --dry-run; then
    echo -e "${GREEN}✓ Renewal test successful${NC}"
else
    echo -e "${YELLOW}⚠ Renewal test failed (not critical)${NC}"
fi

# Setup cron job
echo ""
echo "Setting up auto-renewal cron job..."

CRON_CMD="0 0,12 * * * certbot renew --quiet --post-hook 'systemctl reload nginx'"

# Check if cron job already exists
if crontab -l 2>/dev/null | grep -q "certbot renew"; then
    echo -e "${YELLOW}⚠ Cron job already exists${NC}"
else
    (crontab -l 2>/dev/null; echo "$CRON_CMD") | crontab -
    echo -e "${GREEN}✓ Cron job created (runs twice daily)${NC}"
fi

echo ""
echo "========================================"
echo -e "${GREEN}✓ SSL Setup Complete!${NC}"
echo "========================================"
echo ""
echo "Next steps:"
echo "1. Update your .env file:"
echo "   SESSION_COOKIE_SECURE=true"
echo "   CORS_ORIGINS=https://$DOMAIN"
echo ""
echo "2. Start/reload nginx:"
echo "   systemctl start nginx"
echo "   systemctl reload nginx"
echo ""
echo "3. Start your application:"
echo "   systemctl start ukg-backend"
echo ""
echo "4. Verify SSL:"
echo "   curl -I https://$DOMAIN"
echo "   # Or visit: https://www.ssllabs.com/ssltest/analyze.html?d=$DOMAIN"
echo ""
echo "5. Monitor certificate expiration:"
echo "   certbot certificates"
echo ""
echo "Certificate will auto-renew 30 days before expiration."
echo "========================================"
