// Generated by scripts/generate_provider_manifest.py. Do not edit by hand.
export const PROVIDER_MANIFEST = {
  "schema_version": "provider-manifest.v1",
  "generated_contract": true,
  "providers": [
    {
      "id": "openai",
      "label": "OpenAI",
      "aliases": [],
      "default_model": "gpt-5.5",
      "models": [
        {
          "id": "gpt-5.5",
          "label": "GPT-5.5",
          "minimum_output_tokens": 16
        }
      ],
      "api_key_environment": [
        "OPENAI_API_KEY"
      ],
      "base_url_environment": "OPENAI_BASE_URL",
      "request_api": "responses",
      "capabilities": {
        "native_streaming": true,
        "buffered_output": true
      },
      "pricing": {
        "status": "unknown",
        "reason": "No owner-approved, time-bounded pricing record is installed."
      }
    },
    {
      "id": "google",
      "label": "Google",
      "aliases": [
        "gemini"
      ],
      "default_model": "gemini-3.1-pro-preview",
      "models": [
        {
          "id": "gemini-3.1-pro-preview",
          "label": "Gemini 3.1 Pro Preview",
          "minimum_output_tokens": 1
        }
      ],
      "api_key_environment": [
        "GOOGLE_API_KEY",
        "GEMINI_API_KEY"
      ],
      "base_url_environment": null,
      "request_api": "generate_content",
      "capabilities": {
        "native_streaming": true,
        "buffered_output": true
      },
      "pricing": {
        "status": "unknown",
        "reason": "No owner-approved, time-bounded pricing record is installed."
      }
    }
  ]
} as const;

export const CONFIGURABLE_PROVIDER_TYPES: string[] = PROVIDER_MANIFEST.providers.map((provider) => provider.id);

export const MODEL_LIBRARY: Record<string, string[]> = Object.fromEntries(
  PROVIDER_MANIFEST.providers.map((provider) => [
    provider.id,
    provider.models.map((model) => model.id),
  ])
);

export const DEFAULT_MODEL_BY_PROVIDER: Record<string, string> = Object.fromEntries(
  PROVIDER_MANIFEST.providers.map((provider) => [provider.id, provider.default_model])
);
