"""DSQP chain primitives.

The first DSQP implementation is deterministic and offline-capable. Later
LLM-assisted construction can replace `_answer_question` without changing the
serialized output contract.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import UTC, datetime
import hashlib
import json
import logging
import re
from typing import Any

from backend.dsqp.dsqp_answer_generator import DSQPAnswerGenerator
from backend.dsqp.dsqp_registry import DSQPRegistry

logger = logging.getLogger(__name__)

COMPONENT_KEYS = [
    "job_role",
    "education",
    "certifications",
    "skills",
    "training",
    "career_path",
    "related_jobs",
]

AXIS_PERSONA_TYPES = {
    8: "knowledge",
    9: "sector",
    10: "regulatory",
    11: "compliance",
}


@dataclass
class ExpandedPersona:
    """Serializable DSQP persona output."""

    persona_id: str
    axis_number: int
    persona_type: str
    name: str
    description: str
    components: dict[str, Any]
    dsqp_chain: list[dict[str, Any]]
    coverage_score: float
    metadata: dict[str, Any] = field(default_factory=dict)
    created_at: str = field(default_factory=lambda: datetime.now(UTC).isoformat())

    def to_dict(self) -> dict[str, Any]:
        return {
            "persona_id": self.persona_id,
            "axis_number": self.axis_number,
            "persona_type": self.persona_type,
            "name": self.name,
            "description": self.description,
            "components": self.components,
            "dsqp_chain": self.dsqp_chain,
            "coverage_score": self.coverage_score,
            "metadata": self.metadata,
            "created_at": self.created_at,
        }


class DSQPChain:
    """Construct one seven-component persona for one persona axis.

    Each component answer is generated by a local-LLM self-questioning step when
    a local model is available (``answer_generator``); any component the model
    does not produce or that fails validation falls back to the deterministic
    offline scaffold, so construction stays offline-capable. The per-step
    ``source`` ("llm"/"deterministic") and the persona ``construction_mode``
    ("llm_assisted"/"hybrid"/"deterministic_offline") record which path ran.
    """

    def __init__(
        self,
        registry: DSQPRegistry | None = None,
        answer_generator: DSQPAnswerGenerator | None = None,
    ):
        self.registry = registry or DSQPRegistry()
        self.answer_generator = answer_generator or DSQPAnswerGenerator()

    def construct(
        self,
        query: str,
        axis_vector: dict[str, Any] | None = None,
        *,
        axis_number: int = 8,
        coordinate_path: str = "default",
        context: dict[str, Any] | None = None,
    ) -> ExpandedPersona:
        if axis_number not in AXIS_PERSONA_TYPES:
            raise ValueError(f"DSQP supports persona axes 8-11, got {axis_number}")

        context = context or {}
        axis_vector = axis_vector or {}
        persona_type = AXIS_PERSONA_TYPES[axis_number]
        template = self.registry.template_for(persona_type)
        keywords = self._keywords(query, coordinate_path, context)

        llm_answers = self.answer_generator.generate(
            persona_type=persona_type,
            query=query,
            coordinate_path=coordinate_path,
            keywords=keywords,
            context=context,
            questions=template["questions"],
        )

        components: dict[str, Any] = {}
        chain: list[dict[str, Any]] = []
        llm_component_count = 0
        for step_number, component_key in enumerate(COMPONENT_KEYS, start=1):
            question = template["questions"][component_key]
            llm_answer = llm_answers.get(component_key)
            if llm_answer is not None:
                answer = self._augment_llm_answer(
                    component_key, llm_answer, query, coordinate_path, context
                )
                source = "llm"
                llm_component_count += 1
            else:
                answer = self._answer_question(
                    component_key,
                    persona_type,
                    query,
                    coordinate_path,
                    keywords,
                    context,
                )
                source = "deterministic"
            components[component_key] = answer
            chain.append(
                {
                    "step": step_number,
                    "component": component_key,
                    "question": question,
                    "answer": answer,
                    "source": source,
                    "axis_number": axis_number,
                    "persona_type": persona_type,
                }
            )

        if llm_component_count == len(COMPONENT_KEYS):
            construction_mode = "llm_assisted"
        elif llm_component_count == 0:
            construction_mode = "deterministic_offline"
        else:
            construction_mode = "hybrid"

        digest = hashlib.sha256(
            json.dumps(
                {
                    "axis_number": axis_number,
                    "coordinate_path": coordinate_path,
                    "query": query,
                    "persona_type": persona_type,
                },
                sort_keys=True,
            ).encode()
        ).hexdigest()[:12]
        title = components["job_role"]["title"]
        coverage_score = self._coverage_score(components)
        try:
            from backend.storage.runtime_settings import get_local_slm_audit_mode

            local_slm_audit_enabled = get_local_slm_audit_mode()
        except Exception:
            local_slm_audit_enabled = True

        persona = ExpandedPersona(
            persona_id=f"dsqp_{axis_number}_{digest}",
            axis_number=axis_number,
            persona_type=persona_type,
            name=title,
            description=f"DSQP-constructed {persona_type} persona for {coordinate_path}",
            components=components,
            dsqp_chain=chain,
            coverage_score=coverage_score,
            metadata={
                "coordinate_path": coordinate_path,
                "axis_vector": axis_vector,
                "query_digest": hashlib.sha256(query.encode()).hexdigest()[:16],
                "construction_mode": construction_mode,
                "llm_component_count": llm_component_count,
                "local_slm_audit": {
                    "mode": "LOCAL_MODEL",
                    "enabled": local_slm_audit_enabled,
                    "reason": "desktop_offline_dsqp_construction",
                },
            },
        )
        self._persist_deliverable(persona)
        return persona

    @staticmethod
    def _persist_deliverable(persona: ExpandedPersona) -> None:
        """Persist DSQP construction output to the app-owned object store when available."""
        try:
            from backend.storage import get_object_store

            key = f"dsqp/{persona.persona_id}.json"
            persona.metadata["object_store"] = {
                "bucket": "deliverables",
                "key": key,
            }
            payload = json.dumps(persona.to_dict(), sort_keys=True).encode("utf-8")
            store = get_object_store()
            store.put(
                "deliverables",
                key,
                payload,
                content_type="application/json",
                metadata={
                    "artifact_type": "dsqp_persona",
                    "persona_id": persona.persona_id,
                    "axis_number": str(persona.axis_number),
                },
            )
            persona.metadata["object_store"]["size_bytes"] = len(payload)
        except Exception as exc:  # pylint: disable=broad-except
            from backend.storage.object_store import raise_if_object_store_required

            raise_if_object_store_required(exc, "deliverable_write")
            logger.debug("DSQP deliverable object persistence skipped: %s", exc)

    @staticmethod
    def _augment_llm_answer(
        component_key: str,
        answer: dict[str, Any],
        query: str,
        coordinate_path: str,
        context: dict[str, Any],
    ) -> dict[str, Any]:
        """Add the deterministic context-only fields the LLM schema omits so
        every component keeps the full shape downstream consumers expect
        (e.g. ``job_role.query_mission``, ``education.domain``)."""
        label = coordinate_path.replace("_", " ").replace(".", " / ")
        domain = str(context.get("risk_domain") or context.get("domain") or "standard")
        merged = dict(answer)
        if component_key == "job_role":
            merged.setdefault("level", context.get("experience_level", "Senior Specialist"))
            merged.setdefault("focus_area", label)
            merged["query_mission"] = query[:240]
        elif component_key == "education":
            merged.setdefault("focus", label)
            merged["domain"] = domain
        elif component_key == "certifications":
            merged.setdefault("required_for", domain)
        elif component_key == "skills":
            merged.setdefault("domain_focus", label)
            merged.setdefault("constraints", context.get("constraints", []))
        elif component_key == "training":
            merged.setdefault("risk_domain", domain)
        return merged

    @staticmethod
    def _keywords(query: str, coordinate_path: str, context: dict[str, Any]) -> list[str]:
        tokens = re.findall(r"[A-Za-z][A-Za-z0-9_-]{2,}", f"{query} {coordinate_path}")
        ignored = {"the", "and", "for", "with", "from", "that", "this", "into", "about"}
        keywords = []
        for token in tokens:
            normalized = token.lower()
            if normalized not in ignored and normalized not in keywords:
                keywords.append(normalized)
        for key in ("risk_domain", "domain", "sector"):
            value = context.get(key)
            if value and str(value).lower() not in keywords:
                keywords.append(str(value).lower())
        return keywords[:8] or ["general", "analysis"]

    def _answer_question(
        self,
        component_key: str,
        persona_type: str,
        query: str,
        coordinate_path: str,
        keywords: list[str],
        context: dict[str, Any],
    ) -> dict[str, Any]:
        domain = str(context.get("risk_domain") or context.get("domain") or "standard")
        label = coordinate_path.replace("_", " ").replace(".", " / ")
        skill_terms = [word.title() for word in keywords[:5]]
        if component_key == "job_role":
            return {
                "title": f"Lead {persona_type.title()} Analyst",
                "level": context.get("experience_level", "Senior Specialist"),
                "focus_area": label,
                "query_mission": query[:240],
            }
        if component_key == "education":
            degree = {
                "knowledge": "PhD or equivalent in applied knowledge systems",
                "sector": "MBA or MS in sector operations",
                "regulatory": "JD, LLM, or regulatory affairs graduate training",
                "compliance": "MS in enterprise compliance or risk governance",
            }[persona_type]
            return {"degree": degree, "focus": label, "domain": domain}
        if component_key == "certifications":
            certs = {
                "knowledge": ["UKG-Certified Scholar", "Evidence Synthesis Practitioner"],
                "sector": ["Six Sigma Black Belt", "Industry Operations Lead"],
                "regulatory": ["Regulatory Affairs Certified", "Policy Analysis Lead"],
                "compliance": ["CAMS", "Enterprise Risk Management Professional"],
            }[persona_type]
            return {"list": certs, "required_for": domain}
        if component_key == "skills":
            return {
                "items": sorted(set(skill_terms + ["Analysis", "Verification", "Risk Review"])),
                "domain_focus": label,
                "constraints": context.get("constraints", []),
            }
        if component_key == "training":
            return {
                "modules": [
                    "DSQP Role Activation",
                    "UKG 17-Axis Reasoning",
                    f"{persona_type.title()} Evidence Review",
                ],
                "risk_domain": domain,
            }
        if component_key == "career_path":
            return {
                "stages": [
                    "Analyst",
                    f"{persona_type.title()} Specialist",
                    f"Lead {persona_type.title()} Analyst",
                ],
                "years_in_field": 12 if domain == "standard" else 15,
            }
        return {
            "overlapping_roles": [
                "Risk Manager",
                "Technical Lead",
                f"{persona_type.title()} Reviewer",
            ],
            "blind_spot_coverage": skill_terms[:3],
        }

    @staticmethod
    def _coverage_score(components: dict[str, Any]) -> float:
        populated = 0
        for key in COMPONENT_KEYS:
            value = components.get(key)
            if isinstance(value, dict) and any(v not in (None, "", [], {}) for v in value.values()):
                populated += 1
        return round(populated / len(COMPONENT_KEYS), 4)
